### ISSUE TITLE
SQL error when setting the "REMOTE_ISF_URL" constant

### ISSUE THREAD

**Issue by Abyss-W4tcher** [volatilityfoundation/volatility3#1005]
**Describe the bug**
SQL error when an ISF url is set.

**Context**
Volatility Version:  2.4.2
Operating System:  Ubuntu
Python Version:  3.11.2
Suspected Operating System:  
Command:  

**To Reproduce**

- Set the "REMOTE_ISF_URL" constant to an arbitrary URL
- Launch any volatility command

**Example output**

```sh
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "/volatility3/volatility3/framework/automagic/__init__.py", line 138, in run
    automagic(context, config_path, requirement, progress_callback)
  File "/volatility3/volatility3/framework/automagic/symbol_cache.py", line 509, in __call__
    self._cache.update(progress_callback)
  File "/volatility3/volatility3/framework/automagic/symbol_cache.py", line 432, in update
    cursor.execute(
sqlite3.OperationalError: near "days": syntax error
```

I also printed the SQL command : 

```sql
SELECT cached FROM cache WHERE local = 0 and cached < datetime('now', -3 days)
```

**Additional information**
By adding quotes around "-3 days", the error seems to disappear :

```diff
diff --git a/volatility3/framework/automagic/symbol_cache.py b/volatility3/framework/automagic/symbol_cache.py
index 29f2cfd0..bb281f8b 100644
--- a/volatility3/framework/automagic/symbol_cache.py
+++ b/volatility3/framework/automagic/symbol_cache.py
@@ -429,7 +429,7 @@ class SqliteCache(CacheManagerInterface):
             progress_callback(0, "Reading remote ISF list")
             cursor = self._database.cursor()
             cursor.execute(
-                f"SELECT cached FROM cache WHERE local = 0 and cached < datetime('now', {self.cache_period})"
+                f"SELECT cached FROM cache WHERE local = 0 and cached < datetime('now', '{self.cache_period}')"
             )
             remote_identifiers = RemoteIdentifierFormat(constants.REMOTE_ISF_URL)
             progress_callback(50, "Reading remote ISF list")
```

**Comment by Abyss-W4tcher** [comment]
Furthemore, I couldn't get the remote ISF functionality to work. 

After reading the code, I noticed a mistake in the "INSERT" query, where two parameters are inverted. Then, I also needed to strip the banners after base64 decoding. It allows developers creating banners.json files to keep the original "linux_banner" symbol generated by dwarf2json, without having to decode it, strip it and re-encode it.


```diff
@@ -438,9 +438,11 @@ class SqliteCache(CacheManagerInterface):
                     {}, operating_system=operating_system
                 )
                 for identifier, location in identifiers:
+                    identifier = identifier.rstrip()
+                    identifier = identifier[:-1] if identifier.endswith(b"\x00") else identifier # Linux banners dumped by dwarf2json end with "\x00\n". If not removed, the banner cannot be matched.
                     cursor.execute(
                         "INSERT OR REPLACE INTO cache(identifier, location, operating_system, local, cached) VALUES (?, ?, ?, ?, datetime('now'))",
-                        (location, identifier, operating_system, False),
+                        (identifier, location, operating_system, False),
                     )
             progress_callback(100, "Reading remote ISF list")
             self._database.commit()
```

Now, it is working :)

**Comment by ikelos** [comment]
Hiya, sorry for the delay in making time for issues and reviews of things.  Thanks very much for spotting this and developing fixes, please could you include your changes in a pull request for review and then we can get them merged in?  I'm happy to do it if you don't want you name on the commit, but that's typically how we ensure we attribute people who've contributed a fix.  5:)
