### ISSUE TITLE
printkey breaks when encountering invalid root node

### ISSUE THREAD

**Issue by superponible** [volatilityfoundation/volatility3#1017]
**Describe the bug**
When printkey is given a key and not a hive offset, it walks through the hives.  If the root node does not have a valid signature, it will backtrace and not continue on to other hives.

**To Reproduce**

1. Use command **$ python vol.py -f ~/data.lime --config ~/config.json printkey --key "Software"**

2. See error
<pre>
Volatility 3 Framework 2.5.2
Progress:  100.00		PDB scanning finished
Last Write Time	Hive Offset	Type	Key	Name	Data	Volatile

-	0x88017ec33000	Key	?\Software	-		-
-	0x88017ec3d000	Key	?\Software	-		-
-	0x88017ec4e000	Key	?\Software	-		-
-	0x88018001a000	Key	?\Software	-		-
-	0x880180017000	Key	?\Software	-		-
2019-08-28 14:38:05.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Classes		False
2019-08-28 14:38:05.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Microsoft		False
2019-08-28 14:38:05.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Policies		False
-	0x88018034d000	Key	?\Software	-		-
-	0x880180361000	Key	?\Software	-		-
-	0x880180410000	Key	?\Software	-		-Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/github/vol.git/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/opt/github/vol.git/volatility3/volatility3/cli/__init__.py", line 447, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/github/vol.git/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/opt/github/vol.git/volatility3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/opt/github/vol.git/volatility3/volatility3/framework/plugins/windows/registry/printkey.py", line 254, in _registry_walker
    node_path = hive.get_key(key, return_list=True)
  File "/opt/github/vol.git/volatility3/volatility3/framework/layers/registry.py", line 180, in get_key
    subkeys = node_key[-1].get_subkeys()
  File "/opt/github/vol.git/volatility3/volatility3/framework/objects/__init__.py", line 968, in __getattr__
    raise AttributeError(
AttributeError: StructType has no attribute: symbol_table_name1!_CELL_DATA.get_subkeys
</pre>

**Expected behavior**
This should output the same as when a key is not found in the hive and it should continue to process other hives looking for the key.

**Comment by superponible** [comment]
After the fix.  The hive that was causing the error is bold.

<pre>
$ python vol.py -f ~/data.lime --config ~/config.json printkey --key "Software"
Volatility 3 Framework 2.5.2
Progress:  100.00		PDB scanning finished
Last Write Time	Hive Offset	Type	Key	Name	Data	Volatile

-	0x88017ec33000	Key	?\Software	-		-
-	0x88017ec3d000	Key	?\Software	-		-
-	0x88017ec4e000	Key	?\Software	-		-
-	0x88018001a000	Key	?\Software	-		-
-	0x880180017000	Key	?\Software	-		-
2018-04-11 23:38:44.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Classes		False
2019-08-28 15:50:18.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Microsoft		False
2019-08-28 16:34:19.000000 	0x880180085000	Key	\SystemRoot\System32\Config\DEFAULT\Software	Policies		False
-	0x88018034d000	Key	?\Software	-		-
-	0x880180361000	Key	?\Software	-		-
-	0x880180410000	Key	?\Software	-		-
**-	0x8801805bf000	Key	?\Software	-		-**
2019-08-28 14:37:16.000000 	0x8801805e8000	Key	\??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT\Software	Classes		False
2019-08-28 16:33:51.000000 	0x8801805e8000	Key	\??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT\Software	Google		False
2019-08-28 14:36:26.000000 	0x8801805e8000	Key	\??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT\Software	Microsoft		False
2019-08-28 16:33:51.000000 	0x8801805e8000	Key	\??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT\Software	Policies		False
2019-08-28 14:38:05.000000 	0x8801805e8000	Key	\??\C:\Windows\ServiceProfiles\LocalService\NTUSER.DAT\Software	VMware, Inc.		False
2019-08-28 14:36:54.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	AppDataLow		False
2019-08-28 14:36:48.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Google		False
2019-08-28 17:32:55.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Microsoft		False
2019-08-28 15:50:40.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Mozilla		False
2019-08-28 14:36:48.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Policies		False
2019-08-28 14:38:05.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	VMware, Inc.		False
2019-08-28 14:36:52.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Wow6432Node		False
2019-08-28 14:39:01.000000 	0x880180980000	Key	\??\C:\Users\Analyst\ntuser.dat\Software	Classes		True
-	0x8801809b4000	Key	?\Software	-		-
-	0x880181261000	Key	?\Software	-		-
-	0x8801818ae000	Key	?\Software	-		-
-	0x880181978000	Key	?\Software	-		-
-	0x8801805b6000	Key	?\Software	-		-
-	0x8801819ed000	Key	?\Software	-		-
-	0x88018228d000	Key	?\Software	-		-
-	0x8801823a5000	Key	?\Software	-		-
-	0x880184bc9000	Key	?\Software	-		-
-	0x880187761000	Key	?\Software	-		-
-	0x880187fee000	Key	?\Software	-		-
-	0x880187ffb000	Key	?\Software	-		-
-	0x88018806f000	Key	?\Software	-		-
-	0x880189841000	Key	?\Software	-		-
-	0x8801898e8000	Key	?\Software	-		-
-	0x880183f26000	Key	?\Software	-		-
-	0x880184d1b000	Key	?\Software	-		-
-	0x88018542d000	Key	?\Software	-		-
-	0x880185441000	Key	?\Software	-		-
-	0x880184461000	Key	?\Software	-		-
-	0x880186055000	Key	?\Software	-		-
-	0x880185ae4000	Key	?\Software	-		-
-	0x880186475000	Key	?\Software	-		-
-	0x88018122a000	Key	?\Software	-		-
-	0x880187acb000	Key	?\Software	-		-
</pre>
