### ISSUE TITLE
get_guid_from_mz not compatible with newer versions of PEFile

### ISSUE THREAD

**Issue by daddycocoaman** [volatilityfoundation/volatility3#1026]
**Describe the bug**
It looks like this commit in `pefile` might have broken `PDBUtility.get_guid_from_mz` since the signature has changed to follow GUID standards. Fortunately, this means the guid can just be referenced by the new `Signature_String` attribute. (https://github.com/erocarrera/pefile/commit/d0d6aafd6e3fcaec8a07d2dfef2a2b7adda18269), 

**Context**
Volatility Version:  2.5.0
Operating System:  N/A
Python Version:  N/A
Suspected Operating System:  N/A
Command:  

**To Reproduce**

1. Call `PDBUtility.get_guid_from_mz` from another plugin.
2. Watch it fail

**Expected behavior**
Calling `PDBUtility.get_guid_from_mz` is successful.

**Example output**
```
Traceback (most recent call last):
  File "/home/dcm/dev/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/dcm/dev/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/home/dcm/dev/volatility3/volatility3/cli/__init__.py", line 447, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/dcm/dev/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/home/dcm/dev/volatility3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/home/dcm/dev/volatility3/development/clr.py", line 199, in _generator
    for strong_name, version in self.get_modules_by_process(
  File "/home/dcm/dev/volatility3/development/clr.py", line 135, in get_modules_by_process
    result = pdbutil.PDBUtility.get_guid_from_mz(context, entry.vol.layer_name, entry.DllBase)
  File "/home/dcm/dev/volatility3/volatility3/framework/symbols/windows/pdbutil.py", line 235, in get_guid_from_mz
    binascii.hexlify(debug_entry.Signature_Data4),
TypeError: a bytes-like object is required, not 'int'
```

**Additional information**
Seems like a simple PR. I can contribute.

**Comment by eve-mem** [comment]
I don't know much about PE files, but if you have a fix for this (and it sounds like you do) then I'd highly recommend raising a PR. I'm sure that would be really helpful.

**Comment by daddycocoaman** [comment]
It looks like my fix might break other things because the rest of the pdbconv/pdbutil code expects different combos of guid, pdb name, and age. I'll work on this a bit. 👍🏿
