### ISSUE TITLE
linux: `module_layout` is replaced by `module_memory` as of 6.4

### ISSUE THREAD

**Issue by vobst** [volatilityfoundation/volatility3#1089]
Currently Volatility fails to determine base addresses and sizes of modules on >= 6.4 kernels. This affects the `lsmod`, `keyboard_notifiers`, and `tty_check`.

For `lsmod`:
```
Traceback (most recent call last):
  File "/opt/vol/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 447, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/vol/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/opt/vol/volatility3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/opt/vol/volatility3/volatility3/framework/plugins/linux/lsmod.py", line 63, in _generator
    mod_size = module.get_init_size() + module.get_core_size()
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/extensions/__init__.py", line 40, in get_init_size
    raise AttributeError(
AttributeError: module -> get_init_size: Unable to determine .init section size of module
```

For `keyboard_notifiers`:
```
Traceback (most recent call last):
  File "/opt/vol/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 447, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/vol/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/opt/vol/volatility3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/opt/vol/volatility3/volatility3/framework/plugins/linux/keyboard_notifiers.py", line 42, in _generator
    handlers = linux.LinuxUtilities.generate_kernel_handler_info(
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 319, in generate_kernel_handler_info
    ] + LinuxUtilities.mask_mods_list(context, kernel.layer_name, mods_list)
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 287, in mask_mods_list
    return [
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 290, in <listcomp>
    mod.get_module_base() & mask,
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/extensions/__init__.py", line 33, in get_module_base
    return self.module_core
  File "/opt/vol/volatility3/volatility3/framework/objects/__init__.py", line 963, in __getattr__
    raise AttributeError(
AttributeError: StructType has no attribute: symbol_table_name1!module.module_core. Did you mean: 'get_module_core'?
```

For `tty_check`:
```
Traceback (most recent call last):
  File "/opt/vol/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 790, in main
    CommandLine().run()
  File "/opt/vol/volatility3/volatility3/cli/__init__.py", line 447, in run
    renderers[args.renderer]().render(constructed.run())
  File "/opt/vol/volatility3/volatility3/cli/text_renderer.py", line 193, in render
    grid.populate(visitor, outfd)
  File "/opt/vol/volatility3/volatility3/framework/renderers/__init__.py", line 245, in populate
    for level, item in self._generator:
  File "/opt/vol/volatility3/volatility3/framework/plugins/linux/tty_check.py", line 45, in _generator
    handlers = linux.LinuxUtilities.generate_kernel_handler_info(
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 319, in generate_kernel_handler_info
    ] + LinuxUtilities.mask_mods_list(context, kernel.layer_name, mods_list)
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 287, in mask_mods_list
    return [
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/__init__.py", line 290, in <listcomp>
    mod.get_module_base() & mask,
  File "/opt/vol/volatility3/volatility3/framework/symbols/linux/extensions/__init__.py", line 33, in get_module_base
    return self.module_core
  File "/opt/vol/volatility3/volatility3/framework/objects/__init__.py", line 963, in __getattr__
    raise AttributeError(
AttributeError: StructType has no attribute: symbol_table_name1!module.module_core. Did you mean: 'get_module_core'?
```

The reason is that the way this information is stored was changed in Commit [ac3b432](https://github.com/torvalds/linux/commit/ac3b43283923440900b4f36ca5f9f0b1ca43b70e#diff-1a8b5118e6eaf5be44fdf51f9bceaf816aec6d96e4a048b8455bcfbca6a680f2) ("module: replace module_layout with module_memory").

I will open a PR with a fix once I find some time, however, I won't be mad if someone beats me to that. Might be a good-first-issue.

**Comment by ikelos** [comment]
This might be one for @atcuno or @gcmoreira...

**Comment by eve-mem** [comment]
@vobst - would you be able to check if the changes from https://github.com/volatilityfoundation/volatility3/pull/1093 fix your issue when you get some time? It's been merged into develop now. 

Hopefully it means we can close issue now🤞

**Comment by vobst** [comment]
> @vobst - would you be able to check if the changes from #1093 fix your issue when you get some time? It's been merged into develop now.
> 
> Hopefully it means we can close issue now🤞

Thanks a lot! :) I will re-run my test cases and see if it works.

**Comment by vobst** [comment]
Successfully tested all three plugins with:

- Ubuntu, 6.5.0-14.14-generic
- Arch Linux, 6.6.7-arch1-1
- openSUSE Tumbleweed, 6.6.7-1
- Fedora 39, 6.6.6-200.fc39.x86_64
- Fedora 38, 6.6.6-100.fc38.x86_64

that were previously failing. Thanks! :)

**Comment by eve-mem** [comment]
Awesome. Thanks for checking that! do you think we can close the issue now?

**Comment by vobst** [comment]
Yes ^^
