### ISSUE TITLE
 TypeError: unsupported operand type(s) for +: 'module' and 'str'

### ISSUE THREAD

**Issue by m0majdalawi** [volatilityfoundation/volatility3#1153]
Volatility 3 Framework 2.7.0
INFO     volatility3.cli: Volatility plugins path: ['/home/kali/Desktop/volatility3/volatility3/plugins', '/home/kali/Desktop/volatility3/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/home/kali/Desktop/volatility3/volatility3/symbols', '/home/kali/Desktop/volatility3/volatility3/framework/symbols']
Traceback (most recent call last):
  File "/home/kali/Desktop/volatility3/volatility3/framework/__init__.py", line 130, in import_files
    new_module = getattr(new_module, component)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'volatility3.plugins' has no attribute 'linux'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/Desktop/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/kali/Desktop/volatility3/volatility3/cli/__init__.py", line 871, in main
    CommandLine().run()
  File "/home/kali/Desktop/volatility3/volatility3/cli/__init__.py", line 312, in run
    failures = framework.import_files(
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Desktop/volatility3/volatility3/framework/__init__.py", line 132, in import_files
    failures += [new_module + "." + component]
                 ~~~~~~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'module' and 'str'

**Comment by ikelos** [comment]
This seems as though volatility hasn't been installed correctly.  As you can see [here](https://github.com/volatilityfoundation/volatility3/blob/develop/volatility3/plugins/linux/__init__.py) the source respository (and therefore what should be installed) includes a file in the volatility3.plugins.linux directory, so the `volatility3.plugins` module should have an attribute `linux`.  Please try ensure a complete clone of the repository is present where you're running volatility, or install it using `pip install volatility3`.
