### ISSUE TITLE
Error analyzing Windows 11 VB dump when looking up `_MM_SESSION_SPACE`

### ISSUE THREAD

**Issue by aleguma** [volatilityfoundation/volatility3#1385]
**Bug**
I am trying to get the information from a Windows 11 VirtualBox VM dump (saved as .raw using the method described here https://d33pdiv3r.com/2024/05/22/virtualbox-vm-memory-dump-easy-step-by-step-tutorial/). When I try to use **windows.pslist** or **windows.pstree** plugins, the output is incomplete and the analysis crashes.

**Context**
Volatility Version:  3 Framework 2.12.0 (latest version available as of 7/12/24, same day as this post)
Operating System:  Windows 10
Python Version:  3.13
Suspected Operating System: Windows 11 
Command:  **python vol.py -f TEST.raw windows.pslist**

**To Reproduce**

1. I create a VM in VB, install Windows 11, and get the memory dump as described in https://d33pdiv3r.com/2024/05/22/virtualbox-vm-memory-dump-easy-step-by-step-tutorial/. 
2. I installed Volatility as instructed, including placing the zipped windows symbols in the path volatility3/symbols.
3. Use command 'python vol.py -vvvvv -f TEST.raw windows.pslist'

**Expected behavior**
I expected to get the full list of running processes in the machine.

**Example output**
> INFO     volatility3.cli: Volatility plugins path: ['C:\\Users\\Administrator\\Desktop\\volatility3-develop\\volatility3\\plugins', 'C:\\Users\\Administrator\\Desktop\\volatility3-develop\\volatility3\\framework\\plugins']
> INFO     volatility3.cli: Volatility symbols path: ['C:\\Users\\Administrator\\Desktop\\volatility3-develop\\volatility3\\symbols', 'C:\\Users\\Administrator\\Desktop\\volatility3-develop\\volatility3\\framework\\symbols']
> DETAIL 3 volatility3.cli: Cache directory used: C:\Users\Administrator\AppData\Roaming\volatility3
> INFO     volatility3.framework.automagic: Detected a windows category plugin
> INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
> DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
> DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.layer_name
> DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
>  **DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel **
>  **DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
> INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
> DETAIL 3 volatility3.framework.layers.resources: Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler, OfflineHandler
> DETAIL 2 volatility3.framework.automagic.symbol_cache: Identified file:///C:/Users/Administrator/Desktop/volatility3-develop/volatility3/symbols/windows/ntkrnlmp.pdb/F9533515F98A1E8105A1491384F2EFC1-1.json.xz as b'ntkrnlmp.pdb|F9533515F98A1E8105A1491384F2EFC1|1'
> INFO     volatility3.framework.automagic: Running automagic: LayerStacker
>  **DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
>  **DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name **
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DETAIL 2 volatility3.framework.automagic.stacker: Stacked Elf64Layer using Elf64Stacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using XenCoreDumpStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
> DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
> DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x1ae000
> DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1ae000
> DETAIL 2 volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using XenCoreDumpStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
> DETAIL 2 volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
> DETAIL 1  **volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
> DETAIL 1  **volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
> **DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name**
>  **DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
>  **DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name **
> DETAIL 1  **volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel **
> DETAIL 1  **volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **
> DETAIL 1  **volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name.memory_layer **
> DETAIL 1  **volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name.memory_layer.base_layer **
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
> DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> DETAIL 1 volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
> DEBUG    volatility3.framework.automagic.stacker: physical_layer maximum_address: 4438835251
> DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'Elf64Layer', 'FileLayer']
> INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
> INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DETAIL 1 volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.kernel.symbol_table_name
> DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
> DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
> DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf8077cc00000
> DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrnlmp.pdb\F9533515F98A1E8105A1491384F2EFC1-1
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
> INFO     volatility3.framework.automagic: Running automagic: KernelModule
> DETAIL 3 volatility3.cli.text_filter: Filters:
> []
> 
> PID     PPID    ImageFileName   Offset(V)       Threads Handles SessionId       Wow64   CreateTime      ExitTime        File output
> INFO     volatility3.schemas: Dependency for validation unavailable: jsonschema
> DEBUG    volatility3.schemas: All validations will report success, even with malformed input
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PO_PROCESS_ENERGY_CONTEXT
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_EPROCESS_QUOTA_BLOCK
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PSP_SESSION_SPACE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PS_SYSCALL_PROVIDER
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PAGEFAULT_HISTORY
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_JOB_ACCESS_STATE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_JOB_CPU_RATE_CONTROL
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_JOB_NET_RATE_CONTROL
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_JOB_NOTIFICATION_INFORMATION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PSP_STORAGE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_IOP_FILE_OBJECT_EXTENSION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ACTIVATION_CONTEXT_DATA
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_CHPEV2_PROCESS_INFO
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ASSEMBLY_STORAGE_MAP
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_EXP_LICENSE_STATE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_NLS_STATE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_DBGKP_ERROR_PORT
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_CI_NGEN_PATHS
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_EX_WNF_SUBSCRIPTION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ETW_EVENT_CALLBACK_CONTEXT
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ETW_SOFT_RESTART_CONTEXT
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ETW_STACK_CACHE
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_DRIVER_PROXY_EXTENSION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ETW_PERFECT_HASH_FUNCTION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_EX_TIMER
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_HAL_PMC_COUNTERS
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_DEVICE_NODE_IOMMU_EXTENSION
> DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_SCSI_REQUEST_BLOCK
> 
> 4       0       System  0x9b053c692040  153     -       N/A     False   2024-12-06 08:26:27.000000 UTC  N/A     Disabled
> 128     4       Registry        0x9b053c731080  4       -       N/A     False   2024-12-06 08:26:26.000000 UTC  N/A     Disabled
> 468     4       smss.exe        0x9b053d95b040  2       -       N/A     False   2024-12-06 08:26:27.000000 UTC  N/A     Disabled
> 
> DEBUG    volatility3.cli: Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\_init_.py", line 198, in _weak_resolve
>     return getattr(self._dict[table_name], get_function)(component_name)
>            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\intermed.py", line 60, in _delegate_function
>     return getattr(self._delegate, name)(*args, **kwargs)
>            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\intermed.py", line 808, in get_type
>     return self.natives.get_type(self.name + constants.BANG + type_name)
>            ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\native.py", line 83, in get_type
>     _native_type, native_format = self._native_dictionary[type_name]
>                                   ~~~~~~~~~^^^^^^^^^^^
> KeyError: '_MM_SESSION_SPACE'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\contexts\_init_.py", line 115, in object
>     object_template = self._symbol_space.get_type(object_type)
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\_init_.py", line 253, in get_type
>     self._resolved[type_name] = self._weak_resolve(SymbolType.TYPE, type_name)  # type: ignore
>                                 ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\_init_.py", line 200, in _weak_resolve
>     raise exceptions.SymbolError(
>     ...<3 lines>...
>     )
> volatility3.framework.exceptions.SymbolError: Type symbol_table_name1!_MM_SESSION_SPACE references missing Type/Symbol/Enum: '_MM_SESSION_SPACE'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\cli\_init_.py", line 505, in run
>     renderer.render(grid)
>     ~~~~~^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\cli\text_renderer.py", line 232, in render
>     grid.populate(visitor, outfd)
>     ~~~~~^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\renderers\_init_.py", line 245, in populate
>     for level, item in self._generator:
>                        ^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\plugins\windows\pslist.py", line 299, in _generator
>     proc.get_session_id(),
>     ~~~~~~~^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\windows\extensions\_init_.py", line 816, in get_session_id
>     session = ntkrnlmp.object(
>         object_type="_MM_SESSION_SPACE", offset=self.Session, absolute=True
>     )
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\contexts\_init_.py", line 263, in object
>     return self._context.object(
>            ~~~~~~~~^
>         object_type=object_type,
>         ^^^^^^^^^^^^^^^^^^^^^^^^
>     ...<3 lines>...
>         **kwargs,
>         ^^^^^^^^^
>     )
>     ^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\contexts\_init_.py", line 117, in object
>     object_template = self._symbol_space.get_enumeration(object_type)
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\_init_.py", line 295, in get_enumeration
>     retval = self._weak_resolve(SymbolType.ENUM, enum_name)
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\_init_.py", line 198, in _weak_resolve
>     return getattr(self._dict[table_name], get_function)(component_name)
>            ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\intermed.py", line 60, in _delegate_function
>     return getattr(self._delegate, name)(*args, **kwargs)
>            ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
>   File "C:\Users\Administrator\Desktop\volatility3-develop\volatility3\framework\symbols\intermed.py", line 526, in get_enumeration
>     raise exceptions.SymbolError(
>     ...<3 lines>...
>     )
> volatility3.framework.exceptions.SymbolError: Enumeration not found in symbol_table_name1 table: _MM_SESSION_SPACE
> 
> Volatility experienced a symbol-related issue:
> symbol_table_name1!_MM_SESSION_SPACE: Enumeration not found in symbol_table_name1 table: _MM_SESSION_SPACE
> 
>         * An invalid symbol table
>         * A plugin requesting a bad symbol
>         * A plugin requesting a symbol from the wrong table
> 
> No further results will be produced

**Additional information**
The same happens with **windows.pstree** plugin. Same error, yielding incomplete output. 
The output for **windows.netstat** or **windows.netscan** seems to be complete (no error reported).

It seems volatility cannot fetch the plugin pslist correctly, as the following lines are repeated in the error:

> **DETAIL 1 volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.kernel **
>  **DETAIL 1 volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.kernel.layer_name **

However, the installed volatility version is up to date. Downloaded the same day of posting this issue.

**Comment by ikelos** [comment]
Ok, so the good news is that your image finds an intel layer, and a windows kernel and loads the symbols for it.  The bad news is that a call to `get_session_id` fails probably because of a lookup on `_MM_SESSION_SPACE` which seems not to exist.  This *should* have thrown a symbol exception but appears not to have and instead threw an exception deep within the guts of the symbol handling code (which is uncommon and unusual).

Sure enough, there is no `_MM_SESSION_SPACE` in the F9533515F98A1E8105A1491384F2EFC11 pdb for ntkrnlmp.pdb and that's one for someone on the windows side (@iMHLv2 given there's no Dave L that originally committed it) to figure out I think.  In the meantime, I need to try and get symbol lookups to fail with a symbol error instead of whatever that was...  5:S

**Comment by ikelos** [comment]
Ok, so, it did actually return a symbol error at the end:
```
Volatility experienced a symbol-related issue:
symbol_table_name1!_MM_SESSION_SPACE: Enumeration not found in symbol_table_name1 table: _MM_SESSION_SPACE
```

So looks like I don't need to solve anything there.  It's now just the question of why _MM_SESSION_SPACE isn't there.

I've added in a check to the `get_session_id` call, which should return a `NotAvailableValue`  and allow the rest of the data to be processed.  I'm going to leave the ticket open for investigation by someone on the windows team though.

Thanks very much for bringing it to our attention!  Please try the latest git commit (d29c23e9) and let us know if the plugins at least give you more complete output...

**Comment by the-rectifier** [comment]
I had the same issues recently. Attached is the output of the latest git where now the plugin runs instead of just exiting with the above error message. 

[log.txt](https://github.com/user-attachments/files/18054338/log.txt)

IIRC this only happened with (any) Windows 11 vms I had, but if you'd like, I can get a sample that specifically triggered this

**Comment by ikelos** [comment]
> I can get a sample that specifically triggered this

I'll leave that one to @iMHLv2 to decide, it's more on the forensics side than the framework side.

**Comment by atcuno** [comment]
The way session information is stored changed in Windows 11. We aware of this, and a fix will be coming very soon. Thank you for the report.

**Comment by Blue756** [comment]
> Ok, so, it did actually return a symbol error at the end:
> 
> ```
> Volatility experienced a symbol-related issue:
> symbol_table_name1!_MM_SESSION_SPACE: Enumeration not found in symbol_table_name1 table: _MM_SESSION_SPACE
> ```
> 
> So looks like I don't need to solve anything there. It's now just the question of why _MM_SESSION_SPACE isn't there.
> 
> I've added in a check to the `get_session_id` call, which should return a `NotAvailableValue` and allow the rest of the data to be processed. I'm going to leave the ticket open for investigation by someone on the windows team though.
> 
> Thanks very much for bringing it to our attention! Please try the latest git commit ([d29c23e](https://github.com/volatilityfoundation/volatility3/commit/d29c23e922d22b5ccce0f4bc2ac439acd695a31c)) and let us know if the plugins at least give you more complete output...

This fixed the same issue for me

**Comment by atcuno** [comment]
This was fixed by https://github.com/volatilityfoundation/volatility3/pull/1399
