### ISSUE TITLE
All calls to `get_name` on registry keys need auditing

### ISSUE THREAD

**Issue by atcuno** [volatilityfoundation/volatility3#1476]
The scheduled task plugin crashed on many samples here:

```
24-12-26 13:29:01 volatility3.cli DEBUG    Traceback (most recent call last):
  File "/home/ub/volatility3/volatility3/cli/__init__.py", line 501, in run
    renderer.render(grid)
  File "/home/ub/volatility3/volatility3/cli/text_renderer.py", line 232, in render
    grid.populate(visitor, outfd)
  File "/home/ub/volatility3/volatility3/framework/renderers/__init__.py", line 241, in populate
    for level, item in self._generator:
  File "/home/ub/volatility3/volatility3/framework/plugins/windows/scheduled_tasks.py", line 1403, in <genexpr>
    (
  File "/home/ub/volatility3/volatility3/framework/plugins/windows/scheduled_tasks.py", line 1381, in _generator
    for task in self._parse_task_key(key, task_name_map):
  File "/home/ub/volatility3/volatility3/framework/plugins/windows/scheduled_tasks.py", line 1241, in _parse_task_key
    task_name = guid_mapping.get(str(key.get_name()), renderers.NotAvailableValue())
                                     ^^^^^^^^^^^^^^
  File "/home/ub/volatility3/volatility3/framework/symbols/windows/extensions/registry.py", line 251, in get_name
    return self.Name.cast("string", max_length=namelength, encoding="latin-1")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

We need to fix this one + audit all calls to `get_name` to ensure they are in a try/except

**Comment by ikelos** [comment]
@superponible, any progress on this?
