### ISSUE TITLE
minimum required python version isn't reported correctly

### ISSUE THREAD

**Issue by iMHLv2** [volatilityfoundation/volatility3#181]
There's a check in the code that appears to raise a RuntimeError if a version of Python3 older than 3.5.3 is used:

https://github.com/volatilityfoundation/volatility3/blob/master/volatility/framework/__init__.py#L123

I happened to have 3.5.2 installed and received the following output instead. I was expecting to see the "Volatility framework requires python version {}.{}.{} or greater".format(*required_python_version))" message.

```
$ python3 --version
Python 3.5.2

$ python3 vol.py --help
Traceback (most recent call last):
  File "vol.py", line 7, in <module>
    import volatility.cli
  File "/home/analyst/volatility3-master/volatility/cli/__init__.py", line 24, in <module>
    import volatility.plugins
  File "/home/analyst/volatility3-master/volatility/plugins/__init__.py", line 15, in <module>
    from volatility.framework import constants
  File "/home/analyst/volatility3-master/volatility/framework/__init__.py", line 12, in <module>
    from volatility.framework import constants, interfaces
  File "/home/analyst/volatility3-master/volatility/framework/interfaces/__init__.py", line 15, in <module>
    from volatility.framework.interfaces import renderers, configuration, context, layers, objects, plugins, symbols, \
  File "/home/analyst/volatility3-master/volatility/framework/interfaces/renderers.py", line 15, in <module>
    from typing import Any, Callable, ClassVar, Generator, Iterable, List, NamedTuple, Optional, TypeVar, Type, Tuple, Union
ImportError: cannot import name 'ClassVar'
```

**Comment by ikelos** [comment]
Ok, this should be resolved.  We were doing imports before the checks (which then pulled in lots of stuff).  Since some imports themselves may break older pythons, I've moved the check.  Shout if this is still an issue...
