### ISSUE TITLE
pdbconv: Unhandled leaf_type: 5392

### ISSUE THREAD

**Issue by tklengyel** [volatilityfoundation/volatility3#182]
I've ran into the following error when trying to parse the PDB of win32k.sys from Windows 10 1903:

```
# python3 /shared/volatility3/volatility/framework/symbols/windows/pdbconv.py --guid 6481ec65b6915b3085536fb3a16a81d11 -p win32k.pdb -o windows10-win32k.json
Traceback (most recent call last):ading TPI layer                                                                                             
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 975, in <module>
    json.dump(convertor.get_json(), f, indent = 2, sort_keys = True)
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 541, in get_json
    self.read_necessary_streams()
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 330, in read_necessary_streams
    self.read_tpi_stream()
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 367, in read_tpi_stream
    output, consumed = self.consume_type(module, offset, length)
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 775, in consume_type
    subfield, sub_consumed = self.consume_type(module, sub_offset, sub_length)
  File "/shared/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 787, in consume_type
    raise TypeError("Unhandled leaf_type: {}".format(leaf_type))
TypeError: Unhandled leaf_type: 5392

**Comment by ikelos** [comment]
Hmmm, thanks for the report!  This looks like it may be a bit of work.  My guess is Microsoft started allowing C++ in their core and up to this point we never had to deal with it so much.  There's a few related/uncaught types in the PDB, notably:

```
LF_NESTTYPE
LF_MFUNCTION
LF_METHODLIST
```

All of which seem to relate to methods (and hence classes), so it'll just take me a little time to get the types in there and fix everything up, but it should be doable.

**Comment by npetroni** [comment]
[win32k.pdb.json.txt](https://github.com/volatilityfoundation/volatility3/files/4195115/win32k.pdb.json.txt)  is a JSON for that file, produced via dia.

**Comment by ikelos** [comment]
Thanks for that, it looks like DIA does some clever name mangling, so what we see as `<unnamed-type-u>`, they reconstruct as something like `_IO_RESOURCE_DESCRIPTOR::<unnamed-type-u>::<unnamed-type-BusNumber>` or similar.

**Comment by tklengyel** [comment]
I'm not familiar with DIA, is that a tool that's publicly available?

**Comment by npetroni** [comment]
DIA is Microsoft's debug library. I built a small prototype around it a few years back to bootstrap Vol3 symbol development. pdbconv is the successor and maintained tool moving forward.

https://docs.microsoft.com/en-us/visualstudio/debugger/debug-interface-access/debug-interface-access-sdk?view=vs-2019

**Comment by jgru** [comment]
Dear @ikelos, as suggested in #516, I tried to use `pdbvconv.py` from the feature-branch `feature/pdbconv-cplusplus-vs19` (Commit: d223d73). I want to let you know, that the conversion of a win32k.pdb-file from a Win10 1809 system fails with a `SymbolError`. For further details please refer to the b/m stacktrace:

```
python3 volatility3/framework/symbols/windows/pdbconv.py --guid c0685fe74deea4bec6f9cc52feac5d231 -f ~/win32k.pdb -o windows10-64-win32k.json
...
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/contexts/__init__.py", line 104, in object
    object_template = self._symbol_space.get_type(object_type)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/__init__.py", line 181, in get_type
    self._resolved[type_name] = self._weak_resolve(SymbolType.TYPE, type_name)  # type: ignore
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/__init__.py", line 139, in _weak_resolve
    return getattr(self._dict[table_name], get_function)(component_name)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/intermed.py", line 54, in _delegate_function
    return getattr(self._delegate, name)(*args, **kwargs)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/intermed.py", line 511, in get_type
    raise exceptions.SymbolError(type_name, self.name, "Unknown symbol: {}".format(type_name))
volatility3.framework.exceptions.SymbolError: Unknown symbol: LF_NESTTYPE

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "volatility3/framework/symbols/windows/pdbconv.py", line 1023, in <module>
    converted_json = convertor.get_json()
  File "volatility3/framework/symbols/windows/pdbconv.py", line 568, in get_json
    self.read_necessary_streams()
  File "volatility3/framework/symbols/windows/pdbconv.py", line 336, in read_necessary_streams
    self.read_tpi_stream()
  File "volatility3/framework/symbols/windows/pdbconv.py", line 344, in read_tpi_stream
    type_references = self._read_info_stream(2, "TPI", self.types)
  File "volatility3/framework/symbols/windows/pdbconv.py", line 397, in _read_info_stream
    output, consumed = self.consume_type(module, offset, length)
  File "volatility3/framework/symbols/windows/pdbconv.py", line 786, in consume_type
    subfield, sub_consumed = self.consume_type(module, sub_offset, sub_length)
  File "volatility3/framework/symbols/windows/pdbconv.py", line 799, in consume_type
    parsed_obj = module.object(object_type = type_handler, offset = offset + consumed)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/contexts/__init__.py", line 200, in object
    return self._context.object(object_type = object_type,
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/contexts/__init__.py", line 106, in object
    object_template = self._symbol_space.get_enumeration(object_type)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/__init__.py", line 217, in get_enumeration
    retval = self._weak_resolve(SymbolType.ENUM, enum_name)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/__init__.py", line 139, in _weak_resolve
    return getattr(self._dict[table_name], get_function)(component_name)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/intermed.py", line 54, in _delegate_function
    return getattr(self._delegate, name)(*args, **kwargs)
  File "/home/user01/.local/lib/python3.8/site-packages/volatility3/framework/symbols/intermed.py", line 438, in get_enumeration
    raise exceptions.SymbolError(enum_name, self.name,
volatility3.framework.exceptions.SymbolError: Enumeration not found in pdb1 table: LF_NESTTYPE
```
Thanks already in advance for having a look at this.  

Best regards
Jan

**Comment by ikelos** [comment]
Hmmm, I just checked out that branch and ran this command `python volatility3/framework/symbols/windows/pdbconv.py -g c0685fe74deea4bec6f9cc52feac5d231 -p win32k.pdb` which worked without errors and the type is defined [here](https://github.com/volatilityfoundation/volatility3/blob/feature/pdbconv-cplusplus-vs19/volatility3/framework/symbols/windows/pdb.json#L1177), so I'm a little confused by what could be going wrong?  The second exception is a bit strange (it seems to think the symbol is an enumeration).  Could you please ensure that the win32k.pdb matches the guid you're using, and check that the pdb.json file contains an LF_LEAFTYPE as in the commit linked above?  Failing that, we'll need more of the top exception to find out where/why the issue is happening...

**Comment by jgru** [comment]
Thanks for getting back to me, @ikelos! Using the most recent commit 796cf69b205e428385cd63dcc67dc40ce469c4a9 from 8 hours ago solved the issue! Thank you very much for making this work!

**Comment by ikelos** [comment]
Ah, yeah, I forgot I made a change based on your previous comment on the other issue, sorry!  You were quite right, the "unknown type" was from earlier code before I included things like the `has_name` field.   Glad it works for you now!  5:)

**Comment by trapframe** [comment]
I have the same issue while running pdbconv on ole32.dll from win7 SP1:

pdbconv.py -g ee489189724f4d47aeccfdb5534824352 -p ole32.pdb -o ~/dev/vol_profiles/wmi/win7/32/


On the develop and stable branches i have:

TypeError: Unhandled leaf_type: 5392

On the feature/pdbconv-cplusplus-vs19 branch i have:

TypeError: Unhandled leaf_type: 10
