### ISSUE TITLE
Says PageInvalidAddressException

### ISSUE THREAD

**Issue by mbhatt1** [volatilityfoundation/volatility3#202]
**BUG**
Invalid Page Address

**Context**
Volatility Version:  3.0.0 beta 1
Operating System:  10.15.3
Python Version:  3.6/3.7.5
Suspected Operating System:  10.15.2
Command:  

**To Reproduce**
>python3.6 vol.py -vvv -f ~/memory/data.lime mac.netstat.Netstat
```
DEBUG    root        : Traceback (most recent call last):
  File "/Users/mbhatt/volatility3/volatility/cli/__init__.py", line 281, in run
    renderers[args.renderer]().render(constructed.run())
  File "/Users/mbhatt/volatility3/volatility/cli/text_renderer.py", line 163, in render
    grid.populate(visitor, outfd)
  File "/Users/mbhatt/volatility3/volatility/framework/renderers/__init__.py", line 196, in populate
    for (level, item) in self._generator:
  File "/Users/mbhatt/volatility3/volatility/framework/plugins/mac/netstat.py", line 80, in _generator
    filter_func = filter_func):
  File "/Users/mbhatt/volatility3/volatility/framework/plugins/mac/netstat.py", line 58, in list_sockets
    for filp, _, _ in mac.MacUtilities.files_descriptors_for_process(darwin_symbols, context, task):
  File "/Users/mbhatt/volatility3/volatility/framework/automagic/mac.py", line 271, in files_descriptors_for_process
    path = vnode.full_path()
  File "/Users/mbhatt/volatility3/volatility/framework/symbols/mac/extensions/__init__.py", line 137, in full_path
    self._do_calc_path(elements, self, self.v_name)
  File "/Users/mbhatt/volatility3/volatility/framework/symbols/mac/extensions/__init__.py", line 128, in _do_calc_path
    self._do_calc_path(ret, vnodeobj.v_parent, vnodeobj.v_parent.v_name)
  File "/Users/mbhatt/volatility3/volatility/framework/objects/__init__.py", line 313, in __getattr__
    return getattr(self.dereference(), attr)
  File "/Users/mbhatt/volatility3/volatility/framework/objects/__init__.py", line 681, in __getattr__
    native_layer_name = self.vol.native_layer_name))
  File "/Users/mbhatt/volatility3/volatility/framework/objects/templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "/Users/mbhatt/volatility3/volatility/framework/objects/__init__.py", line 113, in __new__
    value = cls._unmarshall(context, data_format, object_info)
  File "/Users/mbhatt/volatility3/volatility/framework/objects/__init__.py", line 284, in _unmarshall
    data = context.layers.read(object_info.layer_name, object_info.offset, length)
  File "/Users/mbhatt/volatility3/volatility/framework/interfaces/layers.py", line 511, in read
    return self[layer].read(offset, length, pad)
  File "/Users/mbhatt/volatility3/volatility/framework/layers/linear.py", line 37, in read
    for (offset, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "/Users/mbhatt/volatility3/volatility/framework/layers/intel.py", line 194, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "/Users/mbhatt/volatility3/volatility/framework/layers/intel.py", line 99, in _translate
    entry, position = self._translate_entry(offset)
  File "/Users/mbhatt/volatility3/volatility/framework/layers/intel.py", line 125, in _translate_entry
    "Page Fault at entry " + hex(entry) + " in table " + name)
volatility.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in table page directory pointer

Volatility was unable to read a requested page:
Page error 0xb8 in layer primary (Page Fault at entry 0x0 in table page directory pointer)

	* Memory smear during acquisition (try re-acquiring if possible)
	* An intentionally invalid page lookup (operating system protection)
	* A bug in the plugin/volatility (re-run with -vvv and file a bug)

No further results will be produced
```

**Expected behavior**
Volatility not to be so angry

**Comment by mbhatt1** [comment]
Profile's wrong? Wrong kdk?

**Comment by ikelos** [comment]
I'm sorry volatility seems angry, it's actually a very calm and docile piece of software, but it's complex so the stack traces that it provides to try and be helpful are quite long and can seem angry...  5:P

The last line of the stack trace suggests an attempt at dereferencing a zero pointer in a page table.  The `-vvv` output that we'd need to help us give us more information about what's going on would be before the stack trace happens (where it does all its automagic), but my guess based on what you've provided is that an address that's been read points somewhere that can't be accessed (possibly because the memory acquisition took so long that it changed in between the time the page table was read and the time the memory the page table pointed to was read, known as smear).

Given that the kernel string matched the KDK you had installed, it's unlikely to be using the wrong KDK, and you can run other plugins to determine if they all break, or if it's just netstat that has the issue...

**Comment by ikelos** [comment]
@atcuno Any thoughts on this one?

**Comment by atcuno** [comment]
Hello @mbhatt1 ,

I have a created a branch named issue_202 with a fix for this. Can you please check the code from this branch and then verify that your issue is sorted?

Thanks for the report!
