### ISSUE TITLE
windows.handles.Handles gives an exception

### ISSUE THREAD

**Issue by Obad94** [volatilityfoundation/volatility3#203]
**I ran the windows.handles.Handles plugin but it's giving an exception**

"C:\Users\NED\Desktop\volatility3-master>python vol.py -f C:\Users\NED\Desktop\Memory_Dumps\Windows_8_Dumps\Malware\WanaCryMalicious.vmem windows.handles.Handles
Volatility 3 Framework 1.0.0-beta.1
Progress:    0.00               Scanning primary2 using PdbSignatureScanner
PID     Process Offset  HandleValue     Type    GrantedAccess   Name
Traceback (most recent call last):
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 74, in _get_item
    if not self.context.layers[virtual].is_valid(handle_table_entry.Object):
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\objects\__init__.py", line 715, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_HANDLE_TABLE_ENTRY.Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\NED\Desktop\volatility3-master\volatility\cli\__init__.py", line 489, in main
    CommandLine().run()
  File "C:\Users\NED\Desktop\volatility3-master\volatility\cli\__init__.py", line 292, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\NED\Desktop\volatility3-master\volatility\cli\text_renderer.py", line 163, in render
    grid.populate(visitor, outfd)
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\renderers\__init__.py", line 196, in populate
    for (level, item) in self._generator:
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 299, in _generator
    for entry in self.handles(object_table):
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 276, in handles
    for handle_table_entry in self._make_handle_array(TableCode, table_levels):
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 243, in _make_handle_array
    for x in self._make_handle_array(entry, level - 1, depth):
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 253, in _make_handle_array
    item = self._get_item(entry, handle_value)
  File "C:\Users\NED\Desktop\volatility3-master\volatility\framework\plugins\windows\handles.py", line 89, in _get_item
    "Unable to find the SAR value for decoding handle table pointers (Is capstone installed?)")
AttributeError: Unable to find the SAR value for decoding handle table pointers (Is capstone installed?)"

**Context**
Volatility Version:   Volatility 3
Operating System:  Windows 10
Python Version:   Python 3.7
Suspected Operating System: Windows 8 
Command:  windows.handles.Handles

**Comment by ikelos** [comment]
Hiya, thanks for the report.  Just to rule out the obvious, can you please confirm that you have capstone installed correctly?

Accessing certain structures required to find the handle values in more recent versions of Windows required having capstone installed, so I just want to check that's in place to figure out how best to proceed... 5:)

**Comment by Obad94** [comment]
Thank you ikelos for the quick response.
Issue resolved after installing capstone :)
