### ISSUE TITLE
Linux: Volatility 3 fails searching for the DTB. Potential symbol issues.

### ISSUE THREAD

**Issue by gcmoreira** [volatilityfoundation/volatility3#271]
**Describe the bug**
Volatility fails on initialization when _find_aslr()_ is called. In this case I used **linux.pslist.PsList**, but it happens with any Linux plugin.

To generate the ISF I tried the following commands:
1. Providing kernel debug symbols + system.map
`./dwarf2json linux --elf vmlinux-5.4.0-42-generic --system-map System.map-5.4.0-42-generic | xc -c > linux-image-5.4.0-42-generic.json.xz`

1. The traditional vol2 way, using the _dwarf2json_  _**linux-module-method**_ branch and providing the kernel module with dwarf info + system.map 
`./dwarf2json linux --elf-types module.ko --system-map System.map-5.4.0-42-generic | xc -c > linux-image-5.4.0-42-generic.json.xz`

1. Using all the above.
`./dwarf2json linux --elf-symbols vmlinux-5.4.0-42-generic --elf-types module.ko --system-map System.map-5.4.0-42-generic | xc -c > linux-image-5.4.0-42-generic.json.xz`

All the above with the same issue. See error below.

Volatility reads the ISF but _**task_struct**_ doesn't have the offset of its fields. It fails trying to get the "comm" offset.
As you can see in the image and json below, the **_task_struct_** size matches with the ISF but the type doesn't have any children.

![task_struct_comm](https://user-images.githubusercontent.com/10163796/88642342-b4675780-d103-11ea-928a-33521851b010.png)

The following is the content of the ISF, where we can see that **_task_struct_** has the respective fields with its offsets. This happens with  any of the methods to generate the ISF mentioned above.

```json
    "task_struct": {
      "size": 9216,
      "fields": {
        ...
        "comm": {
          "type": {
            "count": 16,
            "kind": "array",
            "subtype": {
              "kind": "base",
              "name": "char"
            }
          },
          "offset": 2680
        },
```

**Context**
Volatility Version:  1.1.0-beta.1 (master)
Operating System:  Ubuntu 20.04 LTS 
Python Version:  3.8.2
Suspected Operating System:  Ubuntu 18.04.4 amd64 / Stock kernel 5.4.0-42-generic 
Command:  ./vol.py -vvvvvvvvv -f ./ram.lime linux.pslist.PsList  
(but it happens with any linux plugin)

**To Reproduce**

1. Use command 'vol.py -vvvvvvvvv -f ./ram.lime linux.pslist.PsList '
2. See error
```shellsession
$ /home/blah/volatility3/vol.py -vvvvvv -f /home/blah/volatility3/ram.lime linux.pslist.PsList  
Volatility 3 Framework 1.1.0-beta.1
INFO     root        : Volatility plugins path: ['/home/blah/volatility3/volatility/plugins', '/home/blah/volatility3/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/blah/volatility3/volatility/symbols', '/home/blah/volatility3/volatility/framework/symbols']
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/plugins, /home/blah/volatility3/volatility/framework/plugins
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.yarascan based on file: yarascan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.svcscan based on file: windows/svcscan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.callbacks based on file: windows/callbacks
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: No module named 'yara'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.vadyarascan based on file: windows/vadyarascan
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.callbacks, volatility.plugins.windows.svcscan, volatility.plugins.windows.vadyarascan, volatility.plugins.yarascan
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/automagic
Level 7  root        : Cache directory used: /home/blah/.cache/volatility3
INFO     volatility.framework.automagic: Detected a linux category plugin
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.vmlinux
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
INFO     volatility.framework.automagic: Running automagic: LinuxBannerCache
Level 6  volatility.framework.symbols.intermed: Searching for symbols in /home/blah/volatility3/volatility/symbols, /home/blah/volatility3/volatility/framework/symbols
INFO     volatility.framework.automagic.symbol_cache: Building linux caches...
Level 7  volatility.framework.layers.resources: Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, JarHandler
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 6  volatility.framework: Importing from the following paths: /home/blah/volatility3/volatility/framework/layers
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux
Level 8  volatility.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility.framework.automagic.stacker: Stacked LimeLayer using LimeStacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 6  volatility.framework.layers.elf: Exception: Offset 0x0 does not exist within the base layer
Level 8  volatility.framework.automagic.stacker: Attempting to stack using WindowsCrashDump32Stacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using LinuxIntelStacker
DEBUG    volatility.framework.automagic.linux: Identified banner: b'Linux version 5.4.0-42-generic (buildd@lgw01-amd64-023) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)) #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 (Ubuntu 5.4.0-42.46~18.04.1-generic 5.4.44)\n\x00'
INFO     volatility.schemas: Dependency for validation unavailable: jsonschema
DEBUG    volatility.schemas: All validations will report success, even with malformed input
Level 7  volatility.framework.automagic.stacker: Exception during stacking: Member not present in template: comm
Level 6  volatility.framework.automagic.stacker: Traceback (most recent call last):

  File "/home/blah/volatility3/volatility/framework/automagic/stacker.py", line 167, in stack_layer
    new_layer = stacker.stack(context, initial_layer, progress_callback)

  File "/home/blah/volatility3/volatility/framework/automagic/linux.py", line 56, in stack
    kaslr_shift, _ = LinuxUtilities.find_aslr(context,

  File "/home/blah/volatility3/volatility/framework/automagic/linux.py", line 260, in find_aslr
    comm_child_offset = task_symbol.relative_child_offset('comm')

  File "/home/blah/volatility3/volatility/framework/objects/templates.py", line 49, in relative_child_offset
    return self.vol.object_class.VolTemplateProxy.relative_child_offset(self, child)

  File "/home/blah/volatility3/volatility/framework/objects/__init__.py", line 666, in relative_child_offset
    raise IndexError("Member not present in template: {}".format(child))

IndexError: Member not present in template: comm

Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: TypeError - Layer is not the required Architecture: LimeLayer
Level 9  volatility.framework.configuration.requirements: TypeError - Layer is not the required Architecture: FileLayer
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['LimeLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: LinuxSymbolFinder
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.vmlinux

Unsatisfied requirement plugins.PsList.primary: Memory layer for the kernel
Unsatisfied requirement plugins.PsList.vmlinux: Linux kernel symbols

A symbol table requirement was not fulfilled.  Please verify that:
	You have the correct symbol file for the requirement
	The symbol file is under the correct directory or zip file
	The symbol file is named appropriately or contains the correct banner


A translation layer requirement was not fulfilled.  Please verify that:
	A file was provided to create this layer (by -f, --single-location or by config)
	The file exists and is readable
	The necessary symbols are present and identified by volatility
Unable to validate the plugin requirements: ['plugins.PsList.primary', 'plugins.PsList.vmlinux']
```

**Expected behavior**
Volatility3 should initialize correctly and executed the appropriate plugin. In the case of linux.pslist.PsList 
 it should show the list of processes running on the OS.

**Additional information**
The memory dump was acquired using lime from a QEMU virtual machine.

**Comment by ikelos** [comment]
Hiya, can you please ensure that it's not using a cached copy of the JSON by running it again with `vol.py --clear-cache`?

**Comment by ikelos** [comment]
If that's the case, I may try to ensure caching only happens with http/https URIs and not zip or file URIs.

**Comment by gcmoreira** [comment]
Great yes yes! Thanks @ikelos, cleaning the cache it worked.

For the sake of completion of this ticket, that only works with the ISF method 1 of above (kernel debug symbols + system.map).

With ISF method 3 (module.ko + system.map + kernel debug symbols), it gets:
```
...
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!xdp_umem
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!ip_mc_list
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!net_rate_estimator
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!kernfs_open_node
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!module_param_attrs
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!raw_hashinfo
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!bpf_offload_dev
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!bpf_cgroup_storage_map
DEBUG    volatility.framework.symbols: Unresolved reference: vmlinux1!static_key_mod
DEBUG    volatility.framework.automagic.linux: Linux ASLR shift values determined: physical -fffda8200000 virtual 35e00000
PID	PPID	COMM
Level 6  volatility.framework.objects: Void size requested
Traceback (most recent call last):
  File "./vol.py", line 10, in <module>
    volatility.cli.main()
  File "/home/blah/volatility3/volatility/cli/__init__.py", line 510, in main
    CommandLine().run()
  File "/home/blah/volatility3/volatility/cli/__init__.py", line 308, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/blah/volatility3/volatility/cli/text_renderer.py", line 181, in render
    grid.populate(visitor, outfd)
  File "/home/blah/volatility3/volatility/framework/renderers/__init__.py", line 209, in populate
    for (level, item) in self._generator:
  File "/home/blah/volatility3/volatility/framework/plugins/linux/pslist.py", line 53, in _generator
    for task in self.list_tasks(self.context,
  File "/home/blah/volatility3/volatility/framework/plugins/linux/pslist.py", line 85, in list_tasks
    for task in init_task.tasks:
  File "/home/blah/volatility3/volatility/framework/interfaces/objects.py", line 121, in __getattr__
    raise AttributeError
AttributeError
```

and with ISF method 2 (module.ko + system.map):

```
Level 6  volatility.framework.layers.elf: Exception: Offset 0x0 does not exist within the base layer
Level 8  volatility.framework.automagic.stacker: Attempting to stack using WindowsCrashDump32Stacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility.framework.automagic.stacker: Attempting to stack using LinuxIntelStacker
Level 7  volatility.framework.automagic.stacker: Exception during stacking: No strings to compile into a regular expression
Level 6  volatility.framework.automagic.stacker: Traceback (most recent call last):

  File "/home/blah/volatility3/volatility/framework/automagic/stacker.py", line 167, in stack_layer
    new_layer = stacker.stack(context, initial_layer, progress_callback)

  File "/home/blah/volatility3/volatility/framework/automagic/linux.py", line 42, in stack
    mss = scanners.MultiStringScanner([x for x in linux_banners if x is not None])

  File "/home/blah/volatility3/volatility/framework/layers/scanners/__init__.py", line 54, in __init__
    self._patterns.preprocess()

  File "/home/blah/volatility3/volatility/framework/layers/scanners/multiregexp.py", line 21, in preprocess
    raise ValueError("No strings to compile into a regular expression")

ValueError: No strings to compile into a regular expression
```
It would be great if Volatility checks if the ISF file changed, by hashing the content, checking the file time or something like that, and reload the cache automatically. Also, I imagine you will see a lot of new tickets/issues due to this. It would be great to mention it somewhere in the documentation.
Thanks again.

**Comment by ikelos** [comment]
Ok, this should be much improved in `faaa3bf6`.  The contents of zip files are no longer cached (this could still be improved so that remote zip-files can be cached, but it's an uncommon state and not one that requires an immediate fix).  I think that closes this issue, but feel free to reopen if you still feel there's something here that can be fixed further...  5:)
