### ISSUE TITLE
windows cmdline exception errors

### ISSUE THREAD

**Issue by mslaughter93** [volatilityfoundation/volatility3#316]
When running the following command on Volatility 3, i get the following exception errors: 
volatility.framework.exceptions.InvalidAddressException
AttributeError: 'InvalidAddressException' object has no attribute 'layer'

Below is the entire plugin result.

Volatility 3 Framework 1.2.0-beta.1
Progress:    0.00		Scanning primary2 using PdbSignatureScanner
PID	Process	Args

4	System	Required memory at 0x20 is not valid (process exited?)
276	smss.exe	\SystemRoot\System32\smss.exe
460	csrss.exe	%SystemRoot%\system32\csrss.exe ObjectDirectory=\Windows SharedSection=1024,20480,768 Windows=On SubSystemType=Windows ServerDll=basesrv,1 ServerDll=winsrv:UserServerDllInitialization,3 ServerDll=sxssrv,4 ProfileControl=Off MaxRequestThreads=16
528	wininit.exe	wininit.exe
628	services.exe	C:\Windows\system32\services.exe
640	lsass.exe	C:\Windows\system32\lsass.exe
712	svchost.exe	C:\Windows\system32\svchost.exe -k DcomLaunch
756	svchost.exe	C:\Windows\system32\svchost.exe -k RPCSS
860	svchost.exe	C:\Windows\System32\svchost.exe -k LocalServiceNetworkRestricted
896	svchost.exe	C:\Windows\system32\svchost.exe -k netsvcs
960	svchost.exe	C:\Windows\system32\svchost.exe -k LocalService
200	svchost.exe	C:\Windows\system32\svchost.exe -k NetworkService
388	svchost.exe	C:\Windows\system32\svchost.exe -k LocalServiceNoNetwork
1076	spoolsv.exe	C:\Windows\System32\spoolsv.exe
1112	svchost.exe	C:\Windows\system32\svchost.exe -k apphostTraceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/plugins/windows/cmdline.py", line 68, in _generator
    result_text = self.get_cmdline(self.context, self.config["nt_symbols"], proc)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/plugins/windows/cmdline.py", line 55, in get_cmdline
    result_text = peb.ProcessParameters.CommandLine.get_string()
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 717, in __getattr__
    member = template(context = self._context, object_info = object_info)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/objects/templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 120, in __new__
    value = cls._unmarshall(context, data_format, object_info)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/objects/__init__.py", line 307, in _unmarshall
    data = context.layers.read(object_info.layer_name, object_info.offset, length)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/interfaces/layers.py", line 542, in read
    return self[layer].read(offset, length, pad)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/layers/linear.py", line 38, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/layers/intel.py", line 200, in mapping
    raise exceptions.InvalidAddressException(layer_name = layer_name, invalid_address = chunk_offset)
volatility.framework.exceptions.InvalidAddressException

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/vol", line 11, in <module>
    load_entry_point('volatility==1.2.0b1', 'console_scripts', 'vol')()
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/cli/__init__.py", line 515, in main
    CommandLine().run()
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/cli/__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/cli/text_renderer.py", line 179, in render
    grid.populate(visitor, outfd)
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/renderers/__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "/usr/local/lib/python3.8/dist-packages/volatility-1.2.0b1-py3.8.egg/volatility/framework/plugins/windows/cmdline.py", line 78, in _generator
    proc_id, exp.invalid_address, exp.layer)
AttributeError: 'InvalidAddressException' object has no attribute 'layer'

**Comment by ikelos** [comment]
So this was an exception within an exception.  The top level exception will still be happening, but is an InvalidAddressException, meaning that an address we tried to read wasn't mapped in the virtual space.  I expect this to work out at address 0 (a null pointer error) to which there's little we can do to help and it's probably related to the image.  However, if it's not or if you still want to investigate further, please feel free to reopen this issue...  5:)
