### ISSUE TITLE
windows.verinfo Error

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#332]
**Describe the bug**
Getting a `OverflowError` when running the `windows.verinfo` plugin.

**Context**
Volatility Version:  Volatility 3 Framework 1.2.0-beta.1
Operating System:  CentOS Linux 7 (Core)
Python Version:  Python 3.8.3 (default, May 19 2020, 18:47:26) 
Suspected Operating System:  Windows Server 2016
Command:  python /home/dev/volatility3/vol.py -vvv -r json -f dump.dd windows.verinfo

**To Reproduce**
Run `windows.verinfo` plugin on Windows Server 2016

**Expected behavior**
Valid plugin output

**Additional information**
Full -vvv output:
```
Volatility 3 Framework 1.2.0-beta.1
INFO     root        : Volatility plugins path: ['/home/dev/volatility3/volatility/plugins', '/home/dev/volatility3/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/home/dev/volatility3/volatility/symbols', '/home/dev/volatility3/volatility/framework/symbols']
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: /opt/conda/lib/python3.8/site-packages/yara.cpython-38-x86_64-linux-gnu.so: undefined symbol: sk_free
DEBUG    volatility.framework: Failed to import module volatility.plugins.yarascan based on file: yarascan
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.cachedump based on file: windows/cachedump
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: /opt/conda/lib/python3.8/site-packages/yara.cpython-38-x86_64-linux-gnu.so: undefined symbol: sk_free
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.callbacks based on file: windows/callbacks
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.hashdump based on file: windows/hashdump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.lsadump based on file: windows/lsadump
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: /opt/conda/lib/python3.8/site-packages/yara.cpython-38-x86_64-linux-gnu.so: undefined symbol: sk_free
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.svcscan based on file: windows/svcscan
INFO     volatility.plugins.yarascan: Python Yara module not found, plugin (and dependent plugins) not available
DEBUG    volatility.framework: /opt/conda/lib/python3.8/site-packages/yara.cpython-38-x86_64-linux-gnu.so: undefined symbol: sk_free
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.vadyarascan based on file: windows/vadyarascan
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.cachedump, volatility.plugins.windows.callbacks, volatility.plugins.windows.hashdump, volatility.plugins.windows.lsadump, volatility.plugins.windows.svcscan, volatility.plugins.windows.vadyarascan, volatility.plugins.yarascan
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1aa000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VerInfo.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VerInfo
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VerInfo.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntkrnlmp.pdb/D9AA3BF08C8A487FA12ED4A362EF4F17-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf800f4079000

DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_LDRP_DLL_SNAP_CONTEXT
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
Traceback (most recent call last):
  File "/home/dev/volatility3/vol.py", line 10, in <module>
    volatility.cli.main()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 515, in main
    CommandLine().run()
  File "/home/dev/volatility3/volatility/cli/__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/dev/volatility3/volatility/cli/text_renderer.py", line 352, in render
    grid.populate(visitor, final_output)
  File "/home/dev/volatility3/volatility/framework/renderers/__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "/home/dev/volatility3/volatility/framework/plugins/windows/verinfo.py", line 143, in _generator
    (major, minor, product, build) = self.get_version_information(self._context, pe_table_name,
  File "/home/dev/volatility3/volatility/framework/plugins/windows/verinfo.py", line 63, in get_version_information
    for offset, data in dos_header.reconstruct():
  File "/home/dev/volatility3/volatility/framework/symbols/windows/extensions/pe.py", line 110, in reconstruct
    fixed_data = self.fix_image_base(raw_data, nt_header)
  File "/home/dev/volatility3/volatility/framework/symbols/windows/extensions/pe.py", line 77, in fix_image_base
    newval = objects.convert_value_to_data(self.vol.offset, int, nt_header.OptionalHeader.ImageBase.vol.data_format)
  File "/home/dev/volatility3/volatility/framework/objects/__init__.py", line 48, in convert_value_to_data
    return int.to_bytes(value,
OverflowError: int too big to convert
```

**Comment by ikelos** [comment]
Hmmm, this looks to be in the `dos_header.reconstruct` code, it takes an offset (which in this case is too large) and tries to stash it into a certain number of bytes.  We probably need a check on it.  @iMHLv2 would you be able to look into this when you get time?

**Comment by iMHLv2** [comment]
@AsafEitani Would you be able to add a print to the code in the following location and re-run the plugin, then paste the output? 

```
+++ b/volatility/framework/symbols/windows/extensions/pe.py
@@ -74,6 +74,7 @@ class IMAGE_DOS_HEADER(objects.StructType):
         image_base_offset = nt_header.OptionalHeader.ImageBase.vol.offset - self.vol.offset
         image_base_type = nt_header.OptionalHeader.ImageBase.vol.type_name
         member_size = self._context.symbol_space.get_type(image_base_type).size
+        print("{} {} {}".format(self.vol.offset, int, nt_header.OptionalHeader.ImageBase.vol.data_format))
         newval = objects.convert_value_to_data(self.vol.offset, int, nt_header.OptionalHeader.ImageBase.vol.data_format)
         return raw_data[:image_base_offset] + newval + raw_data[image_base_offset + member_size:]
```

@ikelos The value being converted is self.vol.offset. Is it possible to instantiate an object at an address that is too large to fit within an integer? I tried what I expect would be the maximum value and it seems to be handled fine...so I'm not sure how this is happening. Hopefully the debugging output will help. 

```
>>> int.to_bytes(0xffffffffffffffff, length = 8, byteorder = 'little', signed = False)
b'\xff\xff\xff\xff\xff\xff\xff\xff'
```

**Comment by ikelos** [comment]
So I think what's going on is it's using a 32-bit structure (in some way, not sure exactly what decides that) and we try to cram a 64-bit address from the layer directly into that structure, which then throws the exception.

**Comment by atcuno** [comment]
I am reopening this as the previous fix was not complete. 

This bug occurs when [/LARGEADDRESSAWARE](https://docs.microsoft.com/en-us/cpp/build/reference/largeaddressaware-handle-large-addresses?view=msvc-160) is set in the PE header. This allows 32bit executables to be mapped past the 4GB boundary. This then turns the load address into a 64 bit value, which we try to fit into a 32bit field, causing an Overflow error. 

In testing, this commonly occurs with .NET executables.

The issue_332_largeaddressaware branch fixes this fully.

**Comment by ikelos** [comment]
This was merged with the fix, so I'm closing again.  Feel free to reopen if there's a need...  5:)
