### ISSUE TITLE
windows.VadYaraScan has json error

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#367]
**Describe the bug**
When running windows.vadyarascan with yara rule file (I assume it will happen with yara rule as string as well), and there's a hit - json is unable to dump `bytes` type.

output:
```
python C:\Users\user\volatility3\vol.py -vvv -r json -f Win.dd windows.vadyarascan.VadYaraScan --yara-file sig.yar
Volatility 3 Framework 1.2.1-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.cachedump based on file: windows\cachedump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.hashdump based on file: windows\hashdump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.lsadump based on file: windows\lsadump
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.cachedump, volatility.plugins.windows.hashdump, volatility.plugins.windows.lsadump
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan
Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
DEBUG    volatility.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1ab000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.VadYaraScan.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.VadYaraScan
Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - yara_rules requirements only accept str type: None
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.VadYaraScan.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntkrnlmp.pdb\A49E7F0A6806463BAFE80C606367F540-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80171805000

DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NET_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PSP_STORAGE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_WNF_SCOPE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ETW_SOFT_RESTART_CONTEXT
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ETW_STACK_CACHE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ETW_PERFECT_HASH_FUNCTION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_HAL_PMC_COUNTERS
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
DEBUG    volatility.framework.interfaces.layers: Scan Failure: Sections have no size, nothing to scan
Traceback (most recent call last):
  File "C:\Users\user\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 356, in render
    self.output_result(outfd, final_output[1])
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 321, in output_result
    outfd.write(json.dumps(result, indent = 2, sort_keys = True))
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 428, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 404, in _iterencode_dict
    yield from chunks
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 437, in _iterencode
    o = _default(o)
  File "C:\ProgramData\Anaconda3\envs\volatility3\lib\json\encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable
```

**Context**
Volatility Version:  1.2.1-beta.1
Operating System:  Windows 10
Python Version:  3.6.9
Suspected Operating System:  Windows 10 (ntkrnlmp.pdb\A49E7F0A6806463BAFE80C606367F540-1)
Command:  windows.vadyarascan

**To Reproduce**

1. Run vadyarascan with flag `-r json` and a sig file that will result a hit
2. See error

**Expected behavior**
I guess JSON should dump bytes as it does in other plugins (malfind) as text representation and hex.

**Comment by ikelos** [comment]
This is now returned as its hex equivalence (matching the standard and CSV output).  So `b'Windows'` would become `"Value": "57 69 6e 64 6f 77 73"`.
