### ISSUE TITLE
Error while running handles

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#368]
**Describe the bug**
Running the handles plugin result in error:
```
python C:\Users\user\volatility3\vol.py -vvv -r json -f dump.vmem windows.handles.Handles
Volatility 3 Framework 1.2.1-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.cachedump based on file: windows\cachedump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.hashdump based on file: windows\hashdump
DEBUG    volatility.framework: No module named 'Crypto'
DEBUG    volatility.framework: Failed to import module volatility.plugins.windows.lsadump based on file: windows\lsadump
INFO     root        : The following plugins could not be loaded (use -vv to see why): volatility.plugins.windows.cachedump, volatility.plugins.windows.hashdump, volatility.plugins.windows.lsadump
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1a8000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntkrpamp.pdb\C6401D4EE1EC427283A8FA17771EFB53-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x81c0b000

DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
Traceback (most recent call last):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 75, in _get_item
    if not self.context.layers[virtual].is_valid(handle_table_entry.Object):
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 729, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_HANDLE_TABLE_ENTRY.Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 515, in main
    CommandLine().run()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 312, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 352, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\volatility3\volatility\framework\renderers\__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 303, in _generator
    for entry in self.handles(object_table):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 280, in handles
    for handle_table_entry in self._make_handle_array(TableCode, table_levels):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 247, in _make_handle_array
    for x in self._make_handle_array(entry, level - 1, depth):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 257, in _make_handle_array
    item = self._get_item(entry, handle_value)
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 93, in _get_item
    "Unable to find the SAR value for decoding handle table pointers", module = "capstone")
TypeError: __init__() got multiple values for argument 'module'
```

**Context**
Volatility Version: 1.2.1-beta.1
Operating System:  Windows 10
Python Version:  3.6.9
Suspected Operating System:  Windows 8.1
Command:  `python C:\Users\user\volatility3\vol.py -vvv -r json -f dump.vmem windows.handles.Handles`

**To Reproduce**

1. Use command `handles` on Windows 8.1 image
2. See error

**Expected behavior**
Handles should work 5:)

**Comment by ikelos** [comment]
Hehehe, I agree "handles should work 5:)"!  5;P

So this looks like an exception occurred when throwing an exception.  I believe I've fixed it, but I'd appreciate it if you can pull the latest commit and check what happens now.  It may not be able to get suitable results, but it should give more useful information hopefully...  5:S

**Comment by AsafEitani** [comment]
So that keeps getting errors:

```
C:\ProgramData\Anaconda3\python.exe C:\Users\user\volatility3\vol.py -vvv -r json -f C:/Users/user/Desktop/dump.vmem windows.handles.Handles --pid 1068 1320 1348 1380 368 1952 2836 896 3688 3576 3856 2476 3928 3744 3956 3940 1412 1676 3776 3948 2768 1196 3204 3840 2008 2248 3212 456 2692

Volatility 3 Framework 2.0.0-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1a8000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.Handles.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.Handles
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']

Progress:  100.00		Stacking attempts finished
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Handles.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:    0.00		Scanning memory_layer using BytesScanner

Progress:   99.12		Scanning primary using PdbSignatureScanner

Progress:   99.32		Scanning primary using PdbSignatureScanner
DEBUG    volatility.framework.symbols.windows.pdbutil: Using symbol library: ntkrpamp.pdb\C6401D4EE1EC427283A8FA17771EFB53-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x81c0b000

Progress:  100.00		PDB scanning finished                     
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
DEBUG    root        : Traceback (most recent call last):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 76, in _get_item
    if not self.context.layers[virtual].is_valid(handle_table_entry.Object):
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 736, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_HANDLE_TABLE_ENTRY.Object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 315, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 351, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\volatility3\volatility\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 304, in _generator
    for entry in self.handles(object_table):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 281, in handles
    for handle_table_entry in self._make_handle_array(TableCode, table_levels):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 258, in _make_handle_array
    item = self._get_item(entry, handle_value)
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 94, in _get_item
    "Unable to find the SAR value for decoding handle table pointers")
volatility.framework.exceptions.MissingModuleException: Unable to find the SAR value for decoding handle table pointers

Volatility could not import a necessary module: capstone
Unable to find the SAR value for decoding handle table pointers

	* A required python module is not installed (install the module and re-run)

No further results will be produced
```

**Comment by ikelos** [comment]
Ok, the error messages seem fairly explanatory (although the stack trace obscures it because of the `-vvv` output), but it says:

```
Volatility could not import a necessary module: capstone
Unable to find the SAR value for decoding handle table pointers

	* A required python module is not installed (install the module and re-run)
```

I think for the SAR decoding, it requires that capstone be installed?  It's not necessary for every image, and is quite a large dependency, so we try to get by without it, but when we can't we inform the user...

**Comment by AsafEitani** [comment]
That's an incorrect exception message, the code clearly says that it `Unable to find the SAR value for decoding handle table pointer`:
```
# is this the right thing to raise here?
if magic is None:
    if not has_capstone:
        raise AttributeError("Unable to find the SAR value for decoding handle table pointers")
    else:
        raise exceptions.MissingModuleException("capstone",
                                                "Unable to find the SAR value for decoding handle table pointers")
```

Also `capstone` is installed.

And I also concerned by the first exception:
```
DEBUG    root        : Traceback (most recent call last):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\handles.py", line 76, in _get_item
    if not self.context.layers[virtual].is_valid(handle_table_entry.Object):
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 736, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_HANDLE_TABLE_ENTRY.Object
```

**Comment by ikelos** [comment]
Ah, you're right on both fronts.  Thanks for persisting with us!  5:S  So we attempt to access various handle table entries, but it looks as though in certain circumstances this doesn't also resolve to something with an `Object` attribute, so that will need fixing.  The logic on the error message was also reversed, so I've fixed that now, thanks.  5:)  Hopefully the chap that wrote the handles plugin will be able to resolve what's going wrong...  5:)

**Comment by AsafEitani** [comment]
Thanks! 0(:D)

**Comment by iMHLv2** [comment]
@AsafEitani Thanks! I applied a patch for this in the [issue_368_windows_handles_x86_win8](https://github.com/volatilityfoundation/volatility3/tree/issue_368_windows_handles_x86_win8 ) branch. Could you switch to that branch and let me know if it works better?

**Comment by AsafEitani** [comment]
Yes that fixed the issue - Thanks :)

**Comment by seliyyah** [comment]
I know this says it's "closed" but I was seeing the same issue using Volatility 3 Framework 2.0.0 using Ubuntu 20.04.2 LTS.  Ran the usual prefix syntax and appended "windows.handles --pid 8888" to my memory image and received the following: 

        *Volatility could not import a necessary module: capstone
        *Requires capstone to find the SAR value for decoding handle table pointers

	*A required python module is not installed (install the module and re-run)

For those of you not super familiar the message in the error tells you how to resolve this, "install the module and re-run."

In my case:  $ **sudo apt-get install python3-capstone**

Re ran the same command and all fixed! Hope this helps someone some where.
