### ISSUE TITLE
TypeError: super() argument 1 must be type, not Enumeration

### ISSUE THREAD

**Issue by cecio** [volatilityfoundation/volatility3#374]
**Describe the bug**
All the plugins I try on Windows 10 images are failing with the error:

`TypeError: super() argument 1 must be type, not Enumeration`

**Context**
Volatility Version:  2.0.0-beta.1
Operating System:  Linux
Python Version:  3.8.6
Suspected Operating System: Win10  
Command:  python3 vol.py -vvv -f ~/Downloads/win10_image.dmp windows.pslist

**To Reproduce**
1. execute a `git clone` of the latest vol3 release
2. run the command above

Here is the error messages:
```
Volatility 3 Framework 2.0.0-beta.1
INFO     root        : Volatility plugins path: ['/tmp/volatility3/volatility/plugins', '/tmp/volatility3/volatility/framework/plugins']
INFO     root        : Volatility symbols path: ['/tmp/volatility3/volatility/symbols', '/tmp/volatility3/volatility/framework/symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
DEBUG    volatility.framework.automagic.windows: Self-referential pointer not in well-known location, moving to recent windows heuristic
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1aa000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PsList.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PsList
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
INFO     volatility.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/4AA575D54F74465395094B84073867BF1/ntkrnlmp.pdb
DEBUG    volatility.framework.layers.resources: Caching file at: /home/cesare/.cache/volatility3/data_5c2c0d74e7761146928e22a7e21d683ca2d617a40258f74f9ecd23f9dec8ad47e5cd5e37a9a6c931ee4d01c52f386afb4e72124321e85f38e68cda6eb0feff58.cache
DEBUG    volatility.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/4AA575D54F74465395094B84073867BF1/ntkrnlmp.pd_
DEBUG    volatility.framework.symbols.windows.pdbconv: Failed with HTTP Error 404: Not Found
DEBUG    volatility.framework.symbols.windows.pdbconv: Reading DBI streamnload/symbols/ntkrnlmp.pdb/4AA575D54F74465395094B84073867BF1/ntkrnlmp.pd_
DEBUG    volatility.framework.symbols.windows.pdbconv: Reading PDB Info
DEBUG    volatility.framework.symbols.windows.pdbconv: Reading TPI
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PsList.nt_symbols
WARNING  volatility.framework.plugins: Automagic exception occurred: TypeError: super() argument 1 must be type, not Enumeration
Level 9  volatility.framework.plugins: Traceback (most recent call last):
  File "/tmp/volatility3/volatility/framework/automagic/__init__.py", line 131, in run
    automagic(context, config_path, requirement, progress_callback)
  File "/tmp/volatility3/volatility/framework/automagic/pdbscan.py", line 301, in __call__
    self.recurse_symbol_fulfiller(context, valid_kernel, progress_callback)
  File "/tmp/volatility3/volatility/framework/automagic/pdbscan.py", line 103, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdb.py", line 77, in load_windows_symbol_table
    cls.download_pdb_isf(context, guid.upper(), age, pdb_name, progress_callback)
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdb.py", line 176, in download_pdb_isf
    json_output = pdbconv.PdbReader(context, location, progress_callback).get_json()
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 538, in get_json
    self.read_necessary_streams()
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 330, in read_necessary_streams
    self.read_tpi_stream()
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 367, in read_tpi_stream
    output, consumed = self.consume_type(module, offset, length)
  File "/tmp/volatility3/volatility/framework/symbols/windows/pdbconv.py", line 714, in consume_type
    if leaf_type in [
  File "/tmp/volatility3/volatility/framework/objects/__init__.py", line 441, in __eq__
    return super(self) == super(other) and self.choices == other.choices
TypeError: super() argument 1 must be type, not Enumeration


Unsatisfied requirement plugins.PsList.nt_symbols: Windows kernel symbols
```

**Expected behavior**
The pdb should be downloaded and the process list displayed

**Screenshots**
NA

**Additional information**
I started to see this issue after creating a new "clone" of the repository, which probably requested to download again the pdb.

**Comment by ikelos** [comment]
So this alleviates the current error, but another one (unsupported leaf type 4097) crops up, so this is kinda solved, but there's still more work to be done...  5:S

**Comment by ikelos** [comment]
Ok, I think this is (properly) resolved, please feel free to reopen this if it's still a problem.  Sorry for the inconvenience!  5:)

**Comment by cecio** [comment]
I confirm it's working fine now. Thanks for the super-fast fix!! :-)
