### ISSUE TITLE
Unable to parse PE debug header in memory with PDBUtility

### ISSUE THREAD

**Issue by japhlange** [volatilityfoundation/volatility3#382]
**Describe the bug**
1.  `PDBUtility.get_guid_from_mz()` is unable to fetch the PDB GUID from a loaded kernel module (driver) in memory.
- most of the time it is not able to properly construct the PE header in memory
- sometimes it is able to build the header but unable to parse its values

**Context**
Volatility Version:  2.0.0-beta.1
Operating System:  Linux 5.9.10-1-MANJARO
Python Version:  3.8.6
Suspected Operating System:  Windows 10 x64 16299
Command:  `PDBUtility.get_guid_from_mz()`

**To Reproduce**

1. Scan image for modules with `windows.modules` (excerpt below):
```
  |         Offset |           Base |     Size |                      Name |                                           Path | File output
* | 0xc88d39c59760 | 0xf8038ba95000 | 0x8d2000 |              ntoskrnl.exe |              \SystemRoot\system32\ntoskrnl.exe |    Disabled
* | 0xc88d39c595c0 | 0xf8038ba16000 |  0x7f000 |                   hal.dll |                   \SystemRoot\system32\hal.dll |    Disabled
* | 0xc88d39c59430 | 0xf8038c400000 |   0xb000 |                 kdcom.dll |                    \SystemRoot\system32\kd.dll |    Disabled
* | 0xc88d39c59280 | 0xf80ad6170000 |  0xf7000 |              mcupdate.dll | \SystemRoot\system32\mcupdate_GenuineIntel.dll |    Disabled
* | 0xc88d39c58010 | 0xf80ad6270000 |  0x61000 |                 msrpc.sys |         \SystemRoot\System32\drivers\msrpc.sys |    Disabled
* | 0xc88d39c58e70 | 0xf80ad62e0000 |  0x29000 |                ksecdd.sys |        \SystemRoot\System32\drivers\ksecdd.sys |    Disabled
* | 0xc88d39c590f0 | 0xf80ad6310000 |  0x11000 |             werkernel.sys |     \SystemRoot\System32\drivers\werkernel.sys |    Disabled
```
2. Verify file's existence in `volshell`:

```
(primary) >>> db(0xf80ad6270000)
0xf80ad6270000    4d 5a 90 00 03 00 00 00 04 00 00 00 ff ff 00 00    MZ..............
0xf80ad6270010    b8 00 00 00 00 00 00 00 40 00 00 00 00 00 00 00    ........@.......
0xf80ad6270020    00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00    ................
0xf80ad6270030    00 00 00 00 00 00 00 00 00 00 00 00 e0 00 00 00    ................
0xf80ad6270040    0e 1f ba 0e 00 b4 09 cd 21 b8 01 4c cd 21 54 68    ........!..L.!Th
0xf80ad6270050    69 73 20 70 72 6f 67 72 61 6d 20 63 61 6e 6e 6f    is.program.canno
0xf80ad6270060    74 20 62 65 20 72 75 6e 20 69 6e 20 44 4f 53 20    t.be.run.in.DOS.
0xf80ad6270070    6d 6f 64 65 2e 0d 0d 0a 24 00 00 00 00 00 00 00    mode....$.......
```

3. Try to parse GUID

```
(primary) >>> from volatility.framework.symbols.windows.pdb import PDBUtility
(primary) >>> PDBUtility.get_guid_from_mz(self.context, self.current_layer, 0xf80ad6270000)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/japh/bin/volatility3/volatility/framework/symbols/windows/pdb.py", line 135, in get_guid_from_mz
    pe_header = layer.read(offset, max_size)
  File "/home/japh/bin/volatility3/volatility/framework/layers/linear.py", line 38, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "/home/japh/bin/volatility3/volatility/framework/layers/intel.py", line 198, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "/home/japh/bin/volatility3/volatility/framework/layers/intel.py", line 318, in _translate
    return self._translate_swap(self, offset, self._bits_per_register // 2)
  File "/home/japh/bin/volatility3/volatility/framework/layers/intel.py", line 276, in _translate_swap
    return super()._translate(offset)
  File "/home/japh/bin/volatility3/volatility/framework/layers/intel.py", line 104, in _translate
    raise exceptions.PagedInvalidAddressException(self.name, offset, position + 1, entry,
volatility.framework.exceptions.PagedInvalidAddressException: Page Fault at entry 0x0 in page entry
```
4. Sometimes the module can be read, but the method still fails (offset of `hal.dll`):

```
(primary) >>> PDBUtility.get_guid_from_mz(self.context, self.current_layer, 0xf8038ba16000)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/japh/bin/volatility3/volatility/framework/symbols/windows/pdb.py", line 142, in get_guid_from_mz
    pdb_name = debug_entry.PdbFileName.decode("utf-8").strip('\x00')
AttributeError: 'NoneType' object has no attribute 'PdbFileName'
```

**Expected behavior**
Return of proper PDB GUID.

Dumping the module via `windows.modules --dump` constructs a proper PE file whose PE headers can be read by `pefile`, including its debug header. 

**Screenshots**
I can add screenshots if necessary.

**Additional information**
If you need access to the memory image give me a shout, but I think this issue should be reproducible.

**Comment by ikelos** [comment]
So, we don't reconstruct the original PE, and so pefile isn't finding the right information.  I've got a fix, but it uses our reconstruction and then pefile to parse, and I'd prefer to find a way for just pefile to parse this from in memory.  It *looks* like it should just be relocating/adjusting something somewhere, but I need to dig into pefile to see how it's supposed to handle in-memory pe files...

**Comment by ikelos** [comment]
Ok, this should be fixed up.  Please note that the `pdb.py` file was recently renamed to `pdbutil.py` to avoid conflicting with the python debugger (pdb).  This won't solve being unable to read the necessary data (if it's been paged out), but should do much better at rebuild the pe_data and extracting the right guid.  Please feel free to reopen this (or a new issue) if you encounter issues with it...
