### ISSUE TITLE
PrintKey json error

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#384]
**Describe the bug**
Running `PrintKey` plugin with JSON flag on specific offset (of the system hive) resulted in JSON error:
```
python C:\Users\user\volatility3\vol.py -vvv -r json -f F:\memdumps\dump.dmp windows.registry.printkey.PrintKey --offset 211113293807616 --key ControlSet001\Control\ComputerName\ActiveComputerName
Volatility 3 Framework 2.0.0-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1ab000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary.memory_layer
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.PrintKey.primary.memory_layer.base_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.PrintKey
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'WindowsCrashDump64Layer', 'FileLayer']

Progress:  100.00		Stacking attempts finished
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.PrintKey.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:   49.69		Scanning memory_layer using BytesScanner

Progress:    0.00		Scanning primary using PdbSignatureScanner
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntkrnlmp.pdb\AB0880FDD01C4AE1963AFC20A1CD7D1C-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf802ae403000

Progress:  100.00		PDB scanning finished                     
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_KTMNOTIFICATION_PACKET
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
DEBUG    volatility.framework.symbols.windows.extensions.registry: Unexpected node type encountered when traversing subkeys: nt_symbols1!_CM_KEY_INDEX, signature: n
DEBUG    volatility.framework.symbols.windows.extensions.registry: Unexpected node type encountered when traversing subkeys: nt_symbols1!_CM_KEY_INDEX, signature: n
Traceback (most recent call last):
  File "C:\Users\user\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 582, in main
    CommandLine().run()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 315, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 355, in render
    self.output_result(outfd, final_output[1])
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 320, in output_result
    outfd.write(json.dumps(result, indent = 2, sort_keys = True))
  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 201, in encode
    chunks = list(chunks)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 429, in _iterencode
    yield from _iterencode_list(o, _current_indent_level)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 325, in _iterencode_list
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 405, in _iterencode_dict
    yield from chunks
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\ProgramData\Anaconda3\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MultiTypeData is not JSON serializable
```

**Context**
Volatility Version:  2.0.0-beta.1
Operating System:  Windows 10
Python Version:  3.6.9
Suspected Operating System:  Server 2012 R2
Command:  `vol.py -vvv -r json -f F:\memdumps\dump.dmp windows.registry.printkey.PrintKey --offset 211113293807616 --key ControlSet001\Control\ComputerName\ActiveComputerName`

**To Reproduce**
Run printkey plugin with the JSON flag

**Expected behavior**
Probably need to convert some types for it to be JSON serializable

**Comment by ikelos** [comment]
Thanks for spotting this, it was pretty easy to fix up so should be all sorted now.  Feel free to reopen if you're still experiencing the issue...  5:)
