### ISSUE TITLE
DllList page error

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#385]
**Describe the bug**
Getting an error by using vol3 - if I use vol2 that doesn't happen:

```
python C:\Users\user\volatility3\vol.py -vvv -r json -f C:/Users/user/Desktop/dump.dd windows.dlllist.DllList

Volatility 3 Framework 2.0.0-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1ab000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DllList.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DllList
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']

Progress:  100.00		Stacking attempts finished
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DllList.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:   99.69		Scanning memory_layer using BytesScanner
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:   80.00		Scanning memory_layer using BytesScanner

Progress:    0.00		Scanning primary using PdbSignatureScanner
DEBUG    volatility.framework.symbols.windows.pdb: Using symbol library: ntkrnlmp.pdb\AB0880FDD01C4AE1963AFC20A1CD7D1C-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf800a406f000

Progress:  100.00		PDB scanning finished                     
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_LDRP_DLL_SNAP_CONTEXT
DEBUG    root        : Traceback (most recent call last):
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 315, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 351, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\volatility3\volatility\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\dlllist.py", line 143, in _generator
    errors = 'replace'), format_hints.Hex(entry.DllBase),
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 728, in __getattr__
    member = template(context = self._context, object_info = object_info)
  File "C:\Users\user\volatility3\volatility\framework\objects\templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 119, in __new__
    value = cls._unmarshall(context, data_format, object_info)
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 306, in _unmarshall
    data = context.layers.read(object_info.layer_name, object_info.offset, length)
  File "C:\Users\user\volatility3\volatility\framework\interfaces\layers.py", line 532, in read
    return self[layer].read(offset, length, pad)
  File "C:\Users\user\volatility3\volatility\framework\layers\linear.py", line 38, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 198, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 318, in _translate
    return self._translate_swap(self, offset, self._bits_per_register // 2)
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 276, in _translate_swap
    return super()._translate(offset)
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 100, in _translate
    entry, position = self._translate_entry(offset)
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 140, in _translate_entry
    table = self._get_valid_table(base_address)
  File "C:\Users\user\volatility3\volatility\framework\layers\intel.py", line 156, in _get_valid_table
    table = self._context.layers.read(self._base_layer, base_address, self.page_size)
  File "C:\Users\user\volatility3\volatility\framework\interfaces\layers.py", line 532, in read
    return self[layer].read(offset, length, pad)
  File "C:\Users\user\volatility3\volatility\framework\layers\physical.py", line 140, in read
    "Offset outside of the buffer boundaries")
volatility.framework.exceptions.InvalidAddressException: Offset outside of the buffer boundaries

Volatility was unable to read a requested page:
0x439d0ffffc000 in layer memory_layer (Offset outside of the buffer boundaries)

	* The base memory file being incomplete (try re-acquiring if possible)
	* Memory smear during acquisition (try re-acquiring if possible)
	* An intentionally invalid page lookup (operating system protection)
	* A bug in the plugin/volatility (re-run with -vvv and file a bug)

No further results will be produced
```

**Context**
Volatility Version:  2.0.0-beta.1
Operating System:  Windows 10
Python Version:  3.6.9
Suspected Operating System:  Windows 2012 R2 x64
Command:  `python C:\Users\user\volatility3\vol.py -vvv -r json -f C:/Users/user/Desktop/dump.dd windows.dlllist.DllList`

**To Reproduce**

Run full dll list - if ran with --pid parameter - works fine

**Expected behavior**
Maybe that's the memory image but it might indicate some other bug

**Comment by ikelos** [comment]
This is pretty odd.  Whilst we're testing to see whether a page table is good or not (and we've already identified an intel page table with this is suitable, but not descended down it completely) we hit a page that looks wrong (it points way outside of the physical space it's supposed to be mapping into).  Even if I prevent that call from returning, the rest of the page is going to be thrown as invalid.  It looks like the first value we're trying to return is in a virtual address that isn't mapped, and so it falls apart.

It looks like we'd need to check `entry.DllBase` and `entry.SizeOfImage` to see whether they're invalid too...  If we have a totally invalid entry, then I'm not sure what we'd return to the user?  @iMHLv2 any thoughts?  Do we return a row of all `UnreadableValue`s, or don't output at all and just vollog that there was a duff entry found?

**Comment by iMHLv2** [comment]
@ikelos I'd vote for using vollog in this case instead of returning a row of unreadable values.

**Comment by ikelos** [comment]
Ok, I'll go with that @iMHLv2, do you want to code it up or should I?  I'm happy either way (but probably not tonight, it's late and I've a few more notifications to clear up).  5:)

**Comment by AsafEitani** [comment]
I think only printing to vollog will be a problem because there would be DLL's that won't be in the result and if you won't actively look in vollog you would just get partial results.
I would think as a user the best thing is getting an unreadable values and vollog.

**Comment by ikelos** [comment]
Sorry this took so long to get resolved, it turned up at a busy time.  I think I agreed with you that we should go with the NotAvailable values.  It's not quite the right answer, but unparsable seems wrong as does unreadble (although unreadable would be better than unparsable).  Anyway, this should now be resolved, please feel free to reopen this if it's still an issue...
