### ISSUE TITLE
DumpFiles error on non existent attribute of PTE

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#409]
**Describe the bug**
Getting error when trying to dump files by physical offset.
Although that exception - the files are being dumped...

```
C:\ProgramData\Anaconda3\python.exe C:\Users\user\volatility3\vol.py -vvv -r json -o output\scripts -f C:/Users/user/Desktop/dump.vmem windows.dumpfiles.DumpFiles --physaddr 12676216

Volatility 3 Framework 2.0.0-beta.1
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\volatility3\\volatility\\framework\\symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1a8000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']

Progress:  100.00		Stacking attempts finished
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:    0.00		Scanning memory_layer using BytesScanner

Progress:    1.56		Scanning memory_layer using BytesScanner

Progress:    3.13		Scanning memory_layer using BytesScanner

Progress:   99.32		Scanning primary using PdbSignatureScanner
DEBUG    volatility.framework.symbols.windows.pdbutil: Using symbol library: ntkrpamp.pdb\C6401D4EE1EC427283A8FA17771EFB53-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x81c0b000

Progress:  100.00		PDB scanning finished                     
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK 
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
Traceback (most recent call last):
  File "C:\Users\user\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 586, in main
    CommandLine().run()
  File "C:\Users\user\volatility3\volatility\cli\__init__.py", line 317, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\volatility3\volatility\cli\text_renderer.py", line 351, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\volatility3\volatility\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 242, in _generator
    for result in self.process_file_object(self.context, self.config["primary"], self.open, file_obj):
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 156, in process_file_object
    file_handle = DumpFiles.dump_file_producer(file_obj, memory_object, open_method, layer, desired_file_name)
  File "C:\Users\user\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 76, in dump_file_producer
    for memoffset, fileoffset, datasize in memory_object.get_available_pages():
  File "C:\Users\user\volatility3\volatility\framework\symbols\windows\extensions\__init__.py", line 971, in get_available_pages
    subsection_offset = ((mmpte.u.Subsect.SubsectionAddressHigh << 7) |
  File "C:\Users\user\volatility3\volatility\framework\objects\__init__.py", line 736, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_MMPTE_SUBSECTION.SubsectionAddressHigh
```

**Context**
Volatility Version: 2.0.0-beta.1
Operating System:  Windows 10
Python Version: 3.6.9
Suspected Operating System: Windows 8.1
Command:  `C:\ProgramData\Anaconda3\python.exe C:\Users\user\volatility3\vol.py -vvv -r json -o output\scripts -f C:/Users/user/Desktop/dump.vmem windows.dumpfiles.DumpFiles --physaddr 12676216`

**To Reproduce**

1. use dump files
2. See error

**Comment by iMHLv2** [comment]
@AsafEitani Thanks for the report. From what I can tell, GUID C6401D4EE1EC427283A8FA17771EFB53 is for 6.3.9600.17415 (32-bit) from 2014-10-29 00:32:39. Given that info and the code path where this exception occurred, I believe the issue is limited to:

* Windows 8
* 32-bit 
* Non-PAE samples

I have a couple of questions, if you don't mind:

1. You mentioned that files are still dumped, despite the exception. How many files, were they empty, and if not - did they contain the content you expected to see? 
2. Do you have access to volatility2 to run a comparison command? If so, I'd be curious if you can share the output from something like this:

```
> vol.py -f <sample> --profile=Win81U1x86 dumpfiles -Q 12676216 -D <outputdir>
```

**Comment by iMHLv2** [comment]
@AsafEitani Disregard my request for more details above. I found a sample and can reproduce the issue...so I will have an update shortly.

**Comment by AsafEitani** [comment]
@iMHLv2 Thanks - and yes the files were dumped properly - with trailing null bytes but I think that's OK for the way files are being dumped from memory.
:)

**Comment by iMHLv2** [comment]
Hi @AsafEitani - could you try this again using either the `develop` or the `release/v2.0.0` branch? I believe the combination of #368 and https://github.com/volatilityfoundation/volatility3/pull/416 fixed this problem, but would like you to confirm before we close the ticket. Thank you!

**Comment by AsafEitani** [comment]
Thanks @iMHLv2 , Indeed that fixed the issue, although I'm getting a different exception for a certain file:

```
C:\ProgramData\Anaconda3\python.exe C:\Users\user\Documents\Github\volatility3\vol.py -vvv -r json -o output -f C:\Users\user\Desktop\dump.vmem windows.dumpfiles.DumpFiles --physaddr 954197856

Volatility 3 Framework 2.0.0
INFO     root        : Volatility plugins path: ['C:\\Users\\user\\Documents\\Github\\volatility3\\volatility\\plugins', 'C:\\Users\\user\\Documents\\Github\\volatility3\\volatility\\framework\\plugins']
INFO     root        : Volatility symbols path: ['C:\\Users\\user\\Documents\\Github\\volatility3\\volatility\\symbols', 'C:\\Users\\user\\Documents\\Github\\volatility3\\volatility\\framework\\symbols']
INFO     volatility.framework.automagic: Detected a windows category plugin
INFO     volatility.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
INFO     volatility.framework.automagic: Running automagic: LayerStacker
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
DEBUG    volatility.framework.automagic.windows: DTB was found at: 0x1a8000
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary
Level 9  volatility.framework.configuration.requirements: IndexError - No configuration provided: plugins.DumpFiles.primary.memory_layer
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.automagic.construct_layers: Failed on requirement: plugins.DumpFiles
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
Level 9  volatility.framework.interfaces.configuration: TypeError - virtaddr requirements only accept int type: None
DEBUG    volatility.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']

Progress:  100.00		Stacking attempts finished
INFO     volatility.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility.framework.automagic: Running automagic: WintelHelper
INFO     volatility.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
Level 9  volatility.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.DumpFiles.nt_symbols
DEBUG    volatility.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure

Progress:    0.00		Scanning memory_layer using BytesScanner

Progress:   99.32		Scanning primary using PdbSignatureScanner
DEBUG    volatility.framework.symbols.windows.pdbutil: Using symbol library: ntkrpamp.pdb\C6401D4EE1EC427283A8FA17771EFB53-1
DEBUG    volatility.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x81c0b000

Progress:  100.00		PDB scanning finished                     
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_PAGEFAULT_HISTORY
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_ACCESS_STATE
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_CPU_RATE_CONTROL
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_JOB_NOTIFICATION_INFORMATION
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_FLS_CALLBACK_INFO
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility.framework.symbols: Unresolved reference: nt_symbols1!_SCSI_REQUEST_BLOCK
DEBUG    volatility.plugins.windows.dumpfiles: Unable to dump file at 0x38dfe760
Traceback (most recent call last):
  File "C:\Users\user\Documents\Github\volatility3\vol.py", line 10, in <module>
    volatility.cli.main()
  File "C:\Users\user\Documents\Github\volatility3\volatility\cli\__init__.py", line 587, in main
    CommandLine().run()
  File "C:\Users\user\Documents\Github\volatility3\volatility\cli\__init__.py", line 317, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\Documents\Github\volatility3\volatility\cli\text_renderer.py", line 351, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 242, in _generator
    for result in self.process_file_object(self.context, self.config["primary"], self.open, file_obj):
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 156, in process_file_object
    file_handle = DumpFiles.dump_file_producer(file_obj, memory_object, open_method, layer, desired_file_name)
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\plugins\windows\dumpfiles.py", line 76, in dump_file_producer
    for memoffset, fileoffset, datasize in memory_object.get_available_pages():
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\symbols\windows\extensions\__init__.py", line 1183, in get_available_pages
    vacb_list = self.process_index_array(vacb_array[counter], 2, limit_depth, vacb_list)
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\symbols\windows\extensions\__init__.py", line 1054, in process_index_array
    if vacb_obj.is_valid(shared_cache_map = self):
  File "C:\Users\user\Documents\Github\volatility3\volatility\framework\objects\__init__.py", line 736, in __getattr__
    raise AttributeError("{} has no attribute: {}.{}".format(agg_name, self.vol.type_name, attr))
AttributeError: StructType has no attribute: nt_symbols1!_VACB.is_valid
```

The other files are being dumped successfully - having said that I only tried to dump less then 20 files so I don't know what's the extent of the issue here.
