### ISSUE TITLE
windows dlllist address out of range

### ISSUE THREAD

**Issue by AsafEitani** [volatilityfoundation/volatility3#463]
**Describe the bug**
Running dlllist on specific image causes an AddressOutOfBound error on this code:
```
format_hints.Hex(entry.DllBase), format_hints.Hex(entry.SizeOfImage)
```
both of which causes the error on a specific exe file. I'm guessing the entry is invalid because other variables of that entry are getting unreadable value.

```
DEBUG    root        : Traceback (most recent call last):
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\cli\__init__.py", line 317, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\cli\text_renderer.py", line 351, in render
    grid.populate(visitor, final_output)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\plugins\windows\dlllist.py", line 143, in _generator
    errors = 'replace'), format_hints.Hex(entry.DllBase),
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\objects\__init__.py", line 728, in __getattr__
    member = template(context = self._context, object_info = object_info)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\objects\templates.py", line 72, in __call__
    return self.vol.object_class(context = context, object_info = object_info, **arguments)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\objects\__init__.py", line 119, in __new__
    value = cls._unmarshall(context, data_format, object_info)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\objects\__init__.py", line 306, in _unmarshall
    data = context.layers.read(object_info.layer_name, object_info.offset, length)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\interfaces\layers.py", line 532, in read
    return self[layer].read(offset, length, pad)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\linear.py", line 37, in read
    for (offset, _, mapped_offset, mapped_length, layer) in self.mapping(offset, length, ignore_errors = pad):
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 204, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 324, in _translate
    return self._translate_swap(self, offset, self._bits_per_register // 2)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 282, in _translate_swap
    return super()._translate(offset)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 101, in _translate
    entry, position = self._translate_entry(offset)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 141, in _translate_entry
    table = self._get_valid_table(base_address)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\intel.py", line 162, in _get_valid_table
    table = self._context.layers.read(self._base_layer, base_address, self.page_size)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\interfaces\layers.py", line 532, in read
    return self[layer].read(offset, length, pad)
  File "C:\Users\user\Documents\GitHub\volatility3\volatility\framework\layers\physical.py", line 140, in read
    "Offset outside of the buffer boundaries")
volatility.framework.exceptions.InvalidAddressException: Offset outside of the buffer boundaries

Volatility was unable to read a requested page:
0x439d0ffffc000 in layer memory_layer (Offset outside of the buffer boundaries)

        * The base memory file being incomplete (try re-acquiring if possible)
        * Memory smear during acquisition (try re-acquiring if possible)
        * An intentionally invalid page lookup (operating system protection)
        * A bug in the plugin/volatility (re-run with -vvv and file a bug)

No further results will be produced
```

**Context**
Volatility Version:  1.0.1
Operating System:  Windows 10
Python Version:  3.6.9
Suspected Operating System:  Windows server 2012 R2
Command:  `C:\ProgramData\Anaconda3\python.exe C:\Users\user\Documents\GitHub\volatility3\vol.py -vvvvv -r json -f dump.vmem windows.dlllist.DllList`

**To Reproduce**

1. Use command 'dlllist' on image with apparently invalid dll entry. 
2. See error

**Expected behavior**
Write out on that entry unreadable value as for `DllBase` and `SizeOfImage`.
We should still be able to view all the other dlls even if one is invalid.

**Comment by ikelos** [comment]
This looks a lot like #385.  Is there anything different going on here?

**Comment by AsafEitani** [comment]
Sorry! Totally forgotten I already submitted a issue on that 🤦
