### ISSUE TITLE
Windows SvcScan Plugin Error

### ISSUE THREAD

**Issue by haloforensics** [volatilityfoundation/volatility3#495]
**Describe the bug**
Receiving the following NameError when running the svcscan plugin against various memory images (Windows XP/Windows7)

(python3) PS C:\utilities\volatility> python vol.py -f C:\Evidence\memory\stuxnet.vmem windows.svcscan.SvcScan
Volatility 3 Framework 1.0.1
Progress:  100.00               PDB scanning finished
Offset  Order   PID     Start   State   Type    Name    Display Binary
Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility3.cli.main()
  File "C:\utilities\volatility\volatility3\cli\__init__.py", line 618, in main
    CommandLine().run()
  File "C:\utilities\volatility\volatility3\cli\__init__.py", line 326, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\utilities\volatility\volatility3\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "C:\utilities\volatility\volatility3\framework\renderers\__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "C:\utilities\volatility\volatility3\framework\plugins\windows\svcscan.py", line 97, in _generator
    service_table_name = self.create_service_table(self.context, self.config["nt_symbols"], self.config_path)
  File "C:\utilities\volatility\volatility3\framework\plugins\windows\svcscan.py", line 90, in create_service_table
    os.path.join("windows", "services"),
NameError: name 'os' is not defined
(python3) PS C:\utilities\volatility>

**Context**
Volatility Version:  1.0.1 
Operating System:  Windows 10 Pro (10.0.19402)
Python Version:  Conda Env Python 3.7.9
Suspected Operating System:  XP/Win 7
Command:  python vol.py -f C:\Evidence\memory\stuxnet.vmem windows.svcscan.SvcScan

**Comment by ikelos** [comment]
Thanks very much for reporting this!  It should be fixed in `develop` now.  5:)
