### ISSUE TITLE
Filescan takes much longer to analyse a windows dump than volatility 2.

### ISSUE THREAD

**Issue by bonafont** [volatilityfoundation/volatility3#512]
**Describe the bug**
Filescan takes more than an hour to give me a list of files whereas on volatility 2, i get my results in less than a minute for the same dump.
The dump is coming from freshly installed 20H2 build of Windows 10.

**Context**
Volatility Version: c3107986fcc8b4eed480d850e58fdbcc3dd45110
Operating System:  Debian buster 10  4.19.0-16-amd64
Python Version:  Python 3.7.3
Suspected Operating System:  Windows 10
Command:  ```time vol3/vol.py -f test_dumps/real_dump.dmp filescan```

**To Reproduce**

1. Use command ```time vol3/vol.py -f test_dumps/real_dump.dmp filescan```

```
...
0xd08facbc1140  \Windows\Fonts\segoeuil.ttf     216
0xd08facbc1910  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\download_cache 216
0xd08facbc1aa0  \$Directory     216
0xd08facbc2270  \Windows\Prefetch\Op-MSEDGE.EXE-37D25F9A-00000001.pf    216
0xd08facbc2590  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\wdag.dll    216
0xd08facbc2720  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\cache  216
0xd08facbc28b0  \$Directory     216
0xd08facbc2a40  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\warnStateCache 216
0xd08facbc2d60  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\edgeSettings_2.0-2f9188b68640dbf72295f9083a21d674a314721ef06f82db281cbcb052ff8ec1     216
0xd08facbc3080  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\topTraffic    216
0xd08facbc39e0  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_3      216
0xd08facbc41b0  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Secure Preferences       216
0xd08facbc44d0  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\index       216
0xd08facbc4660  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_0      216
0xd08face0d410  \Windows\System32\LogFiles\WMI\RtBackup\EtwRTSgrmEtwSession.etl 216
0xd08face40770  \$NonCachedIo   216
0xd08facf431e0  \Windows\System32\DolbyDecMFT.dll       216
0xd08facf43370  \Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\SetMDL2.ttf        216
0xd08facf43500  \Windows\System32\dciman32.dll  216
0xd08facf43820  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\microsoft_shell_integration.dll     216
0xd08facf43cd0  \Windows\System32\CompPkgSrv.exe        216
0xd08facf43e60  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Favicons 216
0xd08facf44180  \Windows\System32\DolbyDecMFT.dll       216
0xd08facf44310  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libGLESv2.dll   216
0xd08facf444a0  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\WidevineCdm\manifest.json   216
0xd08facf447c0  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libEGL.dll      216
0xd08facf44950  \Windows\System32\CompPkgSrv.exe        216
0xd08facf44ae0  \Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf    216
0xd08facf44c70  \Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf    216
0xd08facf44e00  \Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\Trust Protection Lists\manifest.json        216
0xd08facf45120  \$Directory     216
0xd08facf452b0  \Windows\System32\wbem\WmiPrvSE.exe     216
0xd08facf455d0  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Safe Browsing\ChromeExtMalware.store     216
0xd08facf45760  \Windows\System32\MsSpellCheckingFacility.dll   216
0xd08facf45da0  \Windows\System32\ddraw.dll     216
0xd08facf460c0  \Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Local Storage\leveldb\LOG        216
0xd08facf46250  \Windows\System32\CompPkgSup.dll        216
0xd08facf46570  \Windows\INF\WmiApRpl\WmiApRpl.h        216
0xd08facf46890  \$Directory     216
0xd08facf46a20  \Windows\System32\wbem\Performance\WmiApRpl.ini.ini     216
0xd08facf46bb0  \Windows\System32\en-US\user32.dll.mui  216
0xd08facf47380  \Windows\Prefetch\WMIPRVSE.EXE-E8B8DD29.pf      216
0xd08facf48320  \Windows\System32\PerfStringBackup.INI  216
0xd08facf48c80  \$Directory     216
0xd08facf48e10  \Windows\INF\WmiApRpl\WmiApRpl.ini      216
0xd08facf492c0  \Windows\System32       216^CTraceback (most recent call last):
  File "vol3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/anthony/volatilities/vol3/volatility3/cli/__init__.py", line 618, in main
    CommandLine().run()
  File "/home/anthony/volatilities/vol3/volatility3/cli/__init__.py", line 326, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/anthony/volatilities/vol3/volatility3/cli/text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "/home/anthony/volatilities/vol3/volatility3/framework/renderers/__init__.py", line 211, in populate
    for (level, item) in self._generator:
  File "/home/anthony/volatilities/vol3/volatility3/framework/plugins/windows/filescan.py", line 54, in _generator
    for fileobj in self.scan_files(self.context, self.config['primary'], self.config['nt_symbols']):
  File "/home/anthony/volatilities/vol3/volatility3/framework/plugins/windows/filescan.py", line 48, in scan_files
    for result in poolscanner.PoolScanner.generate_pool_scan(context, layer_name, symbol_table, constraints):
  File "/home/anthony/volatilities/vol3/volatility3/framework/plugins/windows/poolscanner.py", line 294, in generate_pool_scan
    for constraint, header in cls.pool_scan(context, scan_layer, symbol_table, constraints, alignment = alignment):
  File "/home/anthony/volatilities/vol3/volatility3/framework/plugins/windows/poolscanner.py", line 355, in pool_scan
    yield from layer.scan(context, scanner, progress_callback)
  File "/home/anthony/volatilities/vol3/volatility3/framework/interfaces/layers.py", line 236, in scan
    for value in scan_iterator():
  File "/home/anthony/volatilities/vol3/volatility3/framework/interfaces/layers.py", line 484, in _scan_iterator
    for mapped in self.mapping(section_start, section_length, ignore_errors = True):
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 212, in mapping
    chunk_offset, page_size, layer_name = self._translate(offset)
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 339, in _translate
    return self._translate_swap(self, offset, self._bits_per_register // 2)
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 291, in _translate_swap
    return super()._translate(offset)
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 105, in _translate
    entry, position = self._translate_entry(offset)
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 149, in _translate_entry
    table = self._get_valid_table(base_address)
  File "/home/anthony/volatilities/vol3/volatility3/framework/layers/intel.py", line 170, in _get_valid_table
    table = self._context.layers.read(self._base_layer, base_address, self.page_size)
KeyboardInterrupt
vol3/vol.py -vvv -f test_dumps/real_dump.dmp filescan  
168.02s user 0.45s system 99% cpu 2:48.59 total
```
(I just stopped it to show the time difference between vol2 and vol3)
than hangs ```0xd08facf492c0  \Windows\System32``` forever

**Expected behavior**
To finish sooner or around the same time as volatility 2 :
Command used : ``` time vol2/vol.py -f ./test_dumps/real_dump.dmp --profile=Win10x64_19041 filescan```
```
...
0x0000d08facbc1140  32766      1 R--rwd \Device\HarddiskVolume3\Windows\Fonts\segoeuil.ttf
0x0000d08facbc1910     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\download_cache
0x0000d08facbc1aa0     18      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facbc2270     16      0 R----- \Device\HarddiskVolume3\Windows\Prefetch\Op-MSEDGE.EXE-37D25F9A-00000001.pf
0x0000d08facbc2590      7      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\wdag.dll
0x0000d08facbc2720     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\cache
0x0000d08facbc28b0     19      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facbc2a40     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\warnStateCache
0x0000d08facbc2d60     14      0 R--rwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\edgeSettings_2.0-2f9188b68640dbf72295f9083a21d674a314721ef06f82db281cbcb052ff8ec1
0x0000d08facbc3080     16      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\topTraffic
0x0000d08facbc39e0     16      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_3
0x0000d08facbc41b0     15      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Secure Preferences
0x0000d08facbc44d0     14      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\index
0x0000d08facbc4660     16      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_0
0x0000d08face0d410      1      1 RWDr-d \Device\HarddiskVolume3\Windows\System32\LogFiles\WMI\RtBackup\EtwRTSgrmEtwSession.etl
0x0000d08face40770      1      0 RW-rwd \Device\HarddiskVolume3\$NonCachedIo
0x0000d08facf431e0     10      0 R--r-d \Device\HarddiskVolume3\Windows\System32\DolbyDecMFT.dll
0x0000d08facf43370     16      0 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\SetMDL2.ttf
0x0000d08facf43500      8      0 R--r-d \Device\HarddiskVolume3\Windows\System32\dciman32.dll
0x0000d08facf43820      8      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\microsoft_shell_integration.dll
0x0000d08facf43cd0     12      0 R--r-d \Device\HarddiskVolume3\Windows\System32\CompPkgSrv.exe
0x0000d08facf43e60     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Favicons
0x0000d08facf44180     15      0 R--r-d \Device\HarddiskVolume3\Windows\System32\DolbyDecMFT.dll
0x0000d08facf44310      9      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libGLESv2.dll
0x0000d08facf444a0     16      0 R--rw- \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\WidevineCdm\manifest.json
0x0000d08facf447c0      5      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libEGL.dll
0x0000d08facf44950     16      0 R--r-- \Device\HarddiskVolume3\Windows\System32\CompPkgSrv.exe
0x0000d08facf44ae0     14      0 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf
0x0000d08facf44c70  32766      1 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf
0x0000d08facf44e00     16      0 R--rw- \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\Trust Protection Lists\manifest.json
0x0000d08facf45120     18      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf452b0      1      0 R--r-d \Device\HarddiskVolume3\Windows\System32\wbem\WmiPrvSE.exe
0x0000d08facf455d0     15      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Safe Browsing\ChromeExtMalware.store
0x0000d08facf45760     14      0 R--r-d \Device\HarddiskVolume3\Windows\System32\MsSpellCheckingFacility.dll
0x0000d08facf45da0     14      0 R--r-d \Device\HarddiskVolume3\Windows\System32\ddraw.dll
0x0000d08facf460c0     16      0 -W-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Local Storage\leveldb\LOG
0x0000d08facf46250      5      0 R--r-d \Device\HarddiskVolume3\Windows\System32\CompPkgSup.dll
0x0000d08facf46570     16      0 RWD--- \Device\HarddiskVolume3\Windows\INF\WmiApRpl\WmiApRpl.h
0x0000d08facf46890     17      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf46a20     16      0 -W-r-- \Device\HarddiskVolume3\Windows\System32\wbem\Performance\WmiApRpl.ini.ini
0x0000d08facf46bb0  32768      1 R--r-d \Device\HarddiskVolume3\Windows\System32\en-US\user32.dll.mui
0x0000d08facf47380     16      0 R----- \Device\HarddiskVolume3\Windows\Prefetch\WMIPRVSE.EXE-E8B8DD29.pf
0x0000d08facf48320      2      0 RWD--- \Device\HarddiskVolume3\Windows\System32\PerfStringBackup.INI
0x0000d08facf48c80     17      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf48e10      2      0 RWD--- \Device\HarddiskVolume3\Windows\INF\WmiApRpl\WmiApRpl.ini
0x0000d08facf492c0  32766      1 R--rw- \Device\HarddiskVolume3\Windows\System32
vol2/vol.py -f   filescan  
45.58s user 4.29s system 99% cpu 50.288 total
```

**Additional information**
Add any other information about the problem here.

**Comment by ikelos** [comment]
One likely reason is that by default volatility 2 scans the physical space, whereas volatility 3 by default scans the virtual space.  This can be many times larger (particularly in some versions of windows they map a number of pages to the same useless page, although we have mitigations in place for that).  A more fair comparison would be to use `-V` with the volatility 2 filescan plugin.  Volatility 2 also skips unallocated objects, but I don't think that will have a significant impact on the speed.  @iMHLv2 can you think of any other reasons, or anything we could potentially do to speed it up?

**Comment by bonafont** [comment]
So I've just tested the same dump with the ```-V``` args on Volatility 2 with the following command: 
```time vol2/vol.py -V -f ./test_dumps/real_dump.dmp --profile=Win10x64_19041 filescan``` and it didn't changed much : 
```
...
0x0000d08facbc01a0     16      0 R--rwd \Device\HarddiskVolume3\Windows\System32\WaaSMedicPS.dll
0x0000d08facbc0330     26      0 R--rwd \Device\HarddiskVolume3\Windows\System32\Windows.Internal.UI.BioEnrollment.ProxyStub.dll
0x0000d08facbc04c0      6      0 R--rw- \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\icudtl.dat
0x0000d08facbc07e0  32768      1 R--r-d \Device\HarddiskVolume3\Windows\System32\en-US\windows.ui.xaml.dll.mui
0x0000d08facbc0c90     15      0 RW-rwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\BrowserMetrics\BrowserMetrics-6093FB9A-150C.pma
0x0000d08facbc1140  32766      1 R--rwd \Device\HarddiskVolume3\Windows\Fonts\segoeuil.ttf
0x0000d08facbc1910     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\download_cache
0x0000d08facbc1aa0     18      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facbc2270     16      0 R----- \Device\HarddiskVolume3\Windows\Prefetch\Op-MSEDGE.EXE-37D25F9A-00000001.pf
0x0000d08facbc2590      7      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\wdag.dll
0x0000d08facbc2720     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\cache
0x0000d08facbc28b0     19      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facbc2a40     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\local\warnStateCache
0x0000d08facbc2d60     14      0 R--rwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\edgeSettings_2.0-2f9188b68640dbf72295f9083a21d674a314721ef06f82db281cbcb052ff8ec1
0x0000d08facbc3080     16      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\SmartScreen\remote\topTraffic
0x0000d08facbc39e0     16      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_3
0x0000d08facbc41b0     15      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Secure Preferences
0x0000d08facbc44d0     14      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\index
0x0000d08facbc4660     16      0 RWDrwd \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\ShaderCache\GPUCache\data_0
0x0000d08face0d410      1      1 RWDr-d \Device\HarddiskVolume3\Windows\System32\LogFiles\WMI\RtBackup\EtwRTSgrmEtwSession.etl
0x0000d08face40770      1      0 RW-rwd \Device\HarddiskVolume3\$NonCachedIo
0x0000d08facf431e0     10      0 R--r-d \Device\HarddiskVolume3\Windows\System32\DolbyDecMFT.dll
0x0000d08facf43370     16      0 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\SetMDL2.ttf
0x0000d08facf43500      8      0 R--r-d \Device\HarddiskVolume3\Windows\System32\dciman32.dll
0x0000d08facf43820      8      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\microsoft_shell_integration.dll
0x0000d08facf43cd0     12      0 R--r-d \Device\HarddiskVolume3\Windows\System32\CompPkgSrv.exe
0x0000d08facf43e60     16      0 RW-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Favicons
0x0000d08facf44180     15      0 R--r-d \Device\HarddiskVolume3\Windows\System32\DolbyDecMFT.dll
0x0000d08facf44310      9      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libGLESv2.dll
0x0000d08facf444a0     16      0 R--rw- \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\WidevineCdm\manifest.json
0x0000d08facf447c0      5      0 R--r-d \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\swiftshader\libEGL.dll
0x0000d08facf44950     16      0 R--r-- \Device\HarddiskVolume3\Windows\System32\CompPkgSrv.exe
0x0000d08facf44ae0     14      0 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf
0x0000d08facf44c70  32766      1 R--rwd \Device\HarddiskVolume3\Windows\SystemResources\Windows.UI.SettingsAppThreshold\SystemSettings\Assets\Fonts\MemMDL2.2.2.ttf
0x0000d08facf44e00     16      0 R--rw- \Device\HarddiskVolume3\Program Files (x86)\Microsoft\Edge\Application\84.0.522.52\Trust Protection Lists\manifest.json
0x0000d08facf45120     18      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf452b0      1      0 R--r-d \Device\HarddiskVolume3\Windows\System32\wbem\WmiPrvSE.exe
0x0000d08facf455d0     15      0 R--rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Safe Browsing\ChromeExtMalware.store
0x0000d08facf45760     14      0 R--r-d \Device\HarddiskVolume3\Windows\System32\MsSpellCheckingFacility.dll
0x0000d08facf45da0     14      0 R--r-d \Device\HarddiskVolume3\Windows\System32\ddraw.dll
0x0000d08facf460c0     16      0 -W-rw- \Device\HarddiskVolume3\Users\Baseline\AppData\Local\Microsoft\Edge\User Data\Default\Local Storage\leveldb\LOG
0x0000d08facf46250      5      0 R--r-d \Device\HarddiskVolume3\Windows\System32\CompPkgSup.dll
0x0000d08facf46570     16      0 RWD--- \Device\HarddiskVolume3\Windows\INF\WmiApRpl\WmiApRpl.h
0x0000d08facf46890     17      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf46a20     16      0 -W-r-- \Device\HarddiskVolume3\Windows\System32\wbem\Performance\WmiApRpl.ini.ini
0x0000d08facf46bb0  32768      1 R--r-d \Device\HarddiskVolume3\Windows\System32\en-US\user32.dll.mui
0x0000d08facf47380     16      0 R----- \Device\HarddiskVolume3\Windows\Prefetch\WMIPRVSE.EXE-E8B8DD29.pf
0x0000d08facf48320      2      0 RWD--- \Device\HarddiskVolume3\Windows\System32\PerfStringBackup.INI
0x0000d08facf48c80     17      0 RW-rwd \Device\HarddiskVolume3\$Directory
0x0000d08facf48e10      2      0 RWD--- \Device\HarddiskVolume3\Windows\INF\WmiApRpl\WmiApRpl.ini
0x0000d08facf492c0  32766      1 R--rw- \Device\HarddiskVolume3\Windows\System32
44.72s user 4.24s system 99% cpu 48.974 total
```
Still about 45 seconds.

Also, I do wanna point out that I have tested this with different dumps and the results on volatility 3 varies, sometimes it finishes without a hitch, sometimes it hangs without displaying anything, or like the problem above, it hangs in the middle of a scan.

When I say it hangs, it's taking too long time for me to let it finish, I generally let them run for about 30 minutes before stopping them.
It also seems the Windows 10 dumps seems for me to be the unlucky ones too.

All those dumps works fine on Vol2.

**Comment by bonafont** [comment]
After using RAM Capturer from Belkasoft to get a dump ( previously I've been using the NotMyFault.exe utility to generate a BSOD to get a dump), I got much faster results with the filescan plugin. So I think the issue is more related to the way the dump is being created than issues with the plugin.
Therefore I will close my issue.

**Comment by ikelos** [comment]
It would be interesting to know what's different between the two/where the the slow down was happening?  What fileformat the was the generated BSOD?  If it's crashdump format, the `-v` output should have that in the list of stack layers, and it would be easy to test if that's causing the slow down by using the `layerwriter` plugin to write out the crashdump layer to a file (effectively converting it to raw format).  If it was the crashdump layer causing the slow down we can look into it and see if we can make it more efficient?

**Comment by bonafont** [comment]
So the dump generated from the BSOD got me those layers : 
```DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'WindowsCrashDump64Layer', 'FileLayer']```
The dump from Ram Capturer got this : 
```DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']```

Using the layerwriter plugin this is the list i'm getting from the BSOD dump : 
```
base_layer
memory_layer
primary
```

From the RAM Capturer dump : 
```
memory_layer
primary
```
Dumping the base_layer does take a significant amount of time.

But dumping the memory_layer from the BSOD dump does approximately take the same amount of time than the one from the RAM Capturer dump. 

Hope this helps.

**Comment by ikelos** [comment]
Hiya, yeah, if the memory_layer from the BSOD can have plugins run against it at the same speed as the good image, it suggests that the WindowsCrashDump64Layer is inefficient in some way, and we can try and speed it up.  Thanks for checking that!  5:)
