### ISSUE TITLE
Volshell exceptions don't provide enough information

### ISSUE THREAD

**Issue by jfbette** [volatilityfoundation/volatility3#607]
**Describe the bug**

Volshell command experience an unexpected situation when launching with the "-l" option

**Context**
Volatility Version:  Volatility 3 Framework 2.0.0
Operating System:  Ubuntu 20.04.3 LTS
Python Version:  Python 3.8.10
Suspected Operating System:  
Command:  volshell.py

**To Reproduce**

0. Analysing a dump made with LiMe of an Ubuntu 20.04.3 LTS server
1. Use command "python3 ./volshell.py -f /dumps/master1.dump  -s /tmp/symbols/ -l"
2. See error : 
```
Volshell (Volatility 3 Framework) 2.0.0
Progress:  100.00		Stacking attempts finished                 

Volatilty encountered an unexpected situation.


	* Please re-run using with -vvv and file a bug with the output
	* at https://github.com/volatilityfoundation/volatility3/issues

No further results will be produced
```

**Expected behavior**
Launch Volatility3 shell

**Screenshots**
```
# python3 ./volshell.py -f /dumps/master1.dumps  -s /tmp/symbols/ -l -vvv
Volshell (Volatility 3 Framework) 2.0.0
INFO     volatility3.framework.automagic: Detected a linux category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell.vmlinux
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell
Level 9  volatility3.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
INFO     volatility3.framework.automagic: Running automagic: LinuxBannerCache
INFO     volatility3.framework.automagic.symbol_cache: Building linux caches...
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
INFO     volatility3.framework.automagic.mac: No Mac banners found - if this is a mac plugin, please check your symbol files location
DEBUG    volatility3.framework.automagic.linux: Identified banner: b'Linux version 5.4.0-91-generic (buildd@lcy01-amd64-017) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 (Ubuntu 5.4.0-91.102-generic 5.4.151)\n\x00'
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!assoc_array_ptr
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!netns_ipvs
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!mtd_info
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!can_pkg_stats
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!can_rcv_lists_stats
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!can_dev_rcv_lists
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!mpls_route
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!sctp_mib
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!ebt_table
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!dn_dev
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!garp_port
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!mpls_dev
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!mrp_port
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!tipc_bearer
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!pcpu_dstats
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!phylink
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!cfg80211_conn
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!cfg80211_cached_keys
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!cfg80211_cqm_config
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!cfg80211_internal_bss
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!sfp
DEBUG    volatility3.framework.symbols: Unresolved reference: LintelStacker1!libipw_device
DEBUG    volatility3.framework.automagic.linux: Linux ASLR shift values determined: physical 54800000 virtual e200000
DEBUG    volatility3.framework.automagic.linux: DTB was found at: 0x56e0a000
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary.memory_layer
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Volshell.primary.memory_layer.base_layer
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell.vmlinux
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Volshell
Level 9  volatility3.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - pid requirements only accept int type: None
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'LimeLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: LinuxSymbolFinder
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Volshell.vmlinux
DEBUG    volatility3.framework.automagic.symbol_finder: Identified banner: b'Linux version 5.4.0-91-generic (buildd@lcy01-amd64-017) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #102-Ubuntu SMP Fri Nov 5 16:31:28 UTC 2021 (Ubuntu 5.4.0-91.102-generic 5.4.151)\n\x00'
DEBUG    volatility3.framework.automagic.symbol_finder: Using symbol library: file:///tmp/symbols/linux/5.4.0-91-generic_5.4.0-91.102_amd64.json
INFO     volatility3.framework.automagic: Running automagic: KernelModule


DEBUG    volatility3.cli: Traceback (most recent call last):
  File "/dumps/volatility3/volatility3/cli/volshell/__init__.py", line 235, in run
    constructed = plugins.construct_plugin(ctx, automagics, plugin, base_config_path, progress_callback,
  File "/dumps/volatility3/volatility3/framework/plugins/__init__.py", line 49, in construct_plugin
    raise exceptions.UnsatisfiedException(unsatisfied)
volatility3.framework.exceptions.UnsatisfiedException

Volatilty encountered an unexpected situation.


	* Please re-run using with -vvv and file a bug with the output
	* at https://github.com/volatilityfoundation/volatility3/issues

No further results will be produced

```

**Additional information**
Without the "-l" option volshell.py launch successfully

**Comment by ikelos** [comment]
Thanks, the `-l` tries to find a linux kernel in the image and a matching ISF file.  When it can't it throws an error, but I agree the error message is extremely unhelpful, sorry about that.  Without `-l` it just loads the flat physical memory, which you'll then have difficulty running plugins against, so it makes sense that that works, but it's not as useful as you'd expect.

I'll work on improving the error messages so at least you've got more idea what's gone wrong...
