### ISSUE TITLE
Volatility3 Failed to import '/usr/lib/libyara.so' in Kali Linux 

### ISSUE THREAD

**Issue by aryanadi-ic** [volatilityfoundation/volatility3#608]
Hi all,

I'm on MAC OS Sierra 10.12 using Virtual Box, Python 2.7.18.  When I ran # /opt/volatility3/vol.py -f /home/aryanadi/Desktop/mymemory imageinfo then I got this failure using Volatility3 in Kali Linux 2021.2 (i guess...) in virtual box 6.1 : 

Volatility 3 Framework 2.0.0
Failed to import '/usr/lib/libyara.so'
PATH = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games;/usr/lib
Traceback (most recent call last):
  File "/opt/volatility3/vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/opt/volatility3/volatility3/cli/__init__.py", line 625, in main
    CommandLine().run()
  File "/opt/volatility3/volatility3/cli/__init__.py", line 228, in run
    failures = framework.import_files(volatility3.plugins,
  File "/opt/volatility3/volatility3/framework/__init__.py", line 125, in import_files
    failures += import_file(base_module.__name__ + '.' + submodule,
  File "/opt/volatility3/volatility3/framework/__init__.py", line 152, in import_file
    importlib.import_module(module)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/volatility3/volatility3/framework/plugins/yarascan.py", line 17, in <module>
    import yara
  File "/usr/local/lib/python3.9/dist-packages/yara/__init__.py", line 7, in <module>
    from yara.rules import compile
  File "/usr/local/lib/python3.9/dist-packages/yara/rules.py", line 17, in <module>
    from yara.libyara_wrapper import *
  File "/usr/local/lib/python3.9/dist-packages/yara/libyara_wrapper.py", line 315, in <module>
    libyaradll = cdll.LoadLibrary(library)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 452, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/libyara.so: cannot open shared object file: No such file or directory

Then, I ran these:
# apt-get install yara-python>=3.8.0            

E: Unable to locate package yara-python

# apt-get install pefile>=2017.8.1 

E: Unable to locate package pefile

Then I ran ls at the volalitilty3 directory and got this: 
'=2017.8.1'  
'=3.8.0'  
API_CHANGES.md 
development  
doc  
LICENSE.txt 
MANIFEST.in 
mypy.ini 
README.md                
requirements-minimal.txt
requirements.txt 
setup.py
volatility3
vol.py
vol.spec
volshell.py         
volshell.spec

QUESTION: what did I miss? What should I do next in order to get the Volatility3 running well in my Kali Linux debian 64 bit? 

Any enlightment will be appreciated! Thanks! :-)
Aryanadi

**Comment by ikelos** [comment]
Hiya, I'd probably suggest using `pip` to install python packages on kali, rather than the system package manager.  Please try `pip install pefile` and `pip install yara-python` and update this ticket with the results.  Thanks!  5:)

**Comment by ikelos** [comment]
Also, I just spotted that when you did `ls` you had files called `=2017.8.1` and `=3.8.0`.  This means that when you ran `apt-get install yara-python>=3.8.0` it wasn't quoted, and `apt-get install yara-python` was run and the output piped into the file called `=3.8.0`.  As I say, I'd try using pip and make sure you quote any parameters that include a pipe operation (such as `<` or `>`).  I'm going to mark this as closed, because the operating system packaging isn't really an issue with volatility.  Feel free to reopen it if you have more to add...
