### ISSUE TITLE
character maps to <undefined>

### ISSUE THREAD

**Issue by geertsbe** [volatilityfoundation/volatility3#674]
when running the command below in powershell (win10x64)
```
py.exe .\vol.py -f ..\memlen.mem windows.filescan.FileScan | findstr ".kdbx"
```
I get the following error:
```
Traceback (most recent call last):B scanning finished
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\vol.py", line 10, in <module>
    volatility3.cli.main()
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\__init__.py", line 625, in main
    CommandLine().run()
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\framework\renderers\__init__.py", line 218, in populate
    accumulator = function(treenode, accumulator)
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\text_renderer.py", line 173, in visitor
    accumulator.write("{}".format("\t".join(line)))
  File "C:\Users\449263479\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-22: character maps to <undefined>
PS C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop> $set=py.exe .\vol.py -f ..\memlen.mem windows.filescan.FileScan | findstr ".kdbx"
Traceback (most recent call last):B scanning finished
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\vol.py", line 10, in <module>
    volatility3.cli.main()
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\__init__.py", line 625, in main
    CommandLine().run()
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\framework\renderers\__init__.py", line 218, in populate
    accumulator = function(treenode, accumulator)
  File "C:\Users\449263479\OneDrive - Office 365 GPI\Bureaublad\volatility3-develop\volatility3\cli\text_renderer.py", line 173, in visitor
    accumulator.write("{}".format("\t".join(line)))
  File "C:\Users\449263479\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 15-22: character maps to <undefined>
```

Running the command with no piping works fine, the operand > for output file produces the same error. Piping with windows.pstree.PsTree works fine as well.

**Comment by ikelos** [comment]
Hi there, I'm sorry you're running into difficulties, but since this only happens when piping into findstr, it suggests that unicode support in findstr isn't all it could be.  I found this (very old) article online suggesting that findstr doesn't support unicode strings: http://www.toughdev.com/content/2010/09/findstr-and-unicode-strings/.  Its recommendation is to use find.exe, or to use powershell `Select-String -Pattern ‘findable text'”`.  This feels in some way similar to #637 where the terminal was forcing the use of the wrong codepage, only here it's the findstr program.

This doesn't appear to be an issue with volatility itself (particularly since you point out that volatility without the piping runs just fine), so I'm going to mark this as closed.  Do please feel free to update this if you find a solution so that other who encounter similar issues can benefit, and also please feel free to reopen this issue if you think that it's specifically a volatility issue rather than one outside of volatility's code...

**Comment by ikelos** [comment]
Here are some articles about people encountering issues when piping because the encoding isn't set (and therefore uses the default): 
* https://stackoverflow.com/questions/492483/setting-the-correct-encoding-when-piping-stdout-in-python
* http://www.macfreek.nl/memory/Encoding_of_Python_stdout

The recommendation appears to be to `export PYTHONIOENCODING=utf-8` to ensure that utf-8 is always used at the encoding, even when piping.

You might also want to check that you're using python-3.6 or later, which has much improved unicode support on the windows console.  The latest version of volatility 3 should require this, but you haven't included the version of volatility3 you're using...
