### ISSUE TITLE
Hashdump error

### ISSUE THREAD

**Issue by lic-8** [volatilityfoundation/volatility3#678]
Hello,
Can anyone tell me what is going on here ?
Thanks.
```
user@hp-workstation:~/Documents/volatility3$ python3.7 vol.py -vvv -f ../ramdumps/challenge.raw windows.hashdump.Hashdump
Volatility 3 Framework 2.0.2
INFO     volatility3.cli: Volatility plugins path: ['/home/user/Documents/volatility3/volatility3/plugins', '/home/user/Documents/volatility3/volatility3/framework/plugins']
INFO     volatility3.cli: Volatility symbols path: ['/home/user/Documents/volatility3/volatility3/symbols', '/home/user/Documents/volatility3/volatility3/framework/symbols']
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump
INFO     volatility3.framework.automagic: Running automagic: SymbolBannerCache
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: Older windows fixed location self-referential pointers
DEBUG    volatility3.framework.automagic.windows: DtbSelfRefPae test succeeded at 0x185000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x185000
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel.layer_name.memory_layer
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Hashdump
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Hashdump.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0x82604000
DEBUG    volatility3.framework.symbols.windows.pdbutil: Using symbol library: ntkrpamp.pdb/EDD3760CEE2B45D2A63BF8C26EE11FAF-2
DEBUG    volatility3.schemas: Validating JSON against schema...
DEBUG    volatility3.schemas: JSON validated against schema (result cached)
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder    
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Hashdump.kernel
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_KTMNOTIFICATION_PACKET
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_EPROCESS_QUOTA_BLOCK
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PAGEFAULT_HISTORY
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_PSP_CPU_QUOTA_APC
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_JOB_ACCESS_STATE
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ACTIVATION_CONTEXT_DATA
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_FLS_CALLBACK_INFO
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_ASSEMBLY_STORAGE_MAP
DEBUG    volatility3.framework.symbols: Unresolved reference: symbol_table_name1!_SCSI_REQUEST_BLOCK
DEBUG    volatility3.schemas: Validating JSON against schema...
DEBUG    volatility3.schemas: JSON validated against schema (result cached)

User	rid	lmhash	nthash
DEBUG    volatility3.plugins.windows.hashdump: SYSTEM address is None: Did you use the correct profile?

-	-	-	-DEBUG    volatility3.plugins.windows.hashdump: SAM address is None: Did you use the correct profile?

-	-	-	-Traceback (most recent call last):
  File "vol.py", line 10, in <module>
    volatility3.cli.main()
  File "/home/user/Documents/volatility3/volatility3/cli/__init__.py", line 625, in main
    CommandLine().run()
  File "/home/user/Documents/volatility3/volatility3/cli/__init__.py", line 333, in run
    renderers[args.renderer]().render(constructed.run())
  File "/home/user/Documents/volatility3/volatility3/cli/text_renderer.py", line 178, in render
    grid.populate(visitor, outfd)
  File "/home/user/Documents/volatility3/volatility3/framework/renderers/__init__.py", line 212, in populate
    for (level, item) in self._generator:
  File "/home/user/Documents/volatility3/volatility3/framework/plugins/windows/hashdump.py", line 263, in _generator
    bootkey = self.get_bootkey(syshive)
  File "/home/user/Documents/volatility3/volatility3/framework/plugins/windows/hashdump.py", line 88, in get_bootkey
    lsa = cls.get_hive_key(syshive, lsa_base)
  File "/home/user/Documents/volatility3/volatility3/framework/plugins/windows/hashdump.py", line 66, in get_hive_key
    result = hive.get_key(key)
AttributeError: 'NoneType' object has no attribute 'get_key'

```

**Comment by ikelos** [comment]
Thanks very much for letting us know.  This should now be fixed in commit `a6217784`.  Please let us know if there's any issues you're still encountering...  5:)
