### ISSUE TITLE
PDBparsing of ARGLIST sizes breaks

### ISSUE THREAD

**Issue by ikelos** [volatilityfoundation/volatility3#99]
Just a note to keep track, attempting the following:

```
PYTHONPATH="." python volatility/framework/symbols/windows/pdbconv.py -g E5900145FDB14BE5B18137FC2C81C7632 -p ntkrpamp.pdb -o test.json
```

fails with:

```
Traceback (most recent call last):ocessing types                                                                                                  
  File "volatility/framework/symbols/windows/pdbconv.py", line 991, in <module>
    json.dump(convertor.get_json(), f, indent = 2, sort_keys = True)
  File "volatility/framework/symbols/windows/pdbconv.py", line 540, in get_json
    self.read_necessary_streams()
  File "volatility/framework/symbols/windows/pdbconv.py", line 330, in read_necessary_streams
    self.read_tpi_stream()
  File "volatility/framework/symbols/windows/pdbconv.py", line 380, in read_tpi_stream
    self.process_types(type_references)
  File "volatility/framework/symbols/windows/pdbconv.py", line 700, in process_types
    self.user_types = self.replace_forward_references(self.user_types, type_references)
  File "volatility/framework/symbols/windows/pdbconv.py", line 814, in replace_forward_references
    types[k] = self.replace_forward_references(v, type_references)
  File "volatility/framework/symbols/windows/pdbconv.py", line 814, in replace_forward_references
    types[k] = self.replace_forward_references(v, type_references)
  File "volatility/framework/symbols/windows/pdbconv.py", line 814, in replace_forward_references
    types[k] = self.replace_forward_references(v, type_references)
  [Previous line repeated 2 more times]
  File "volatility/framework/symbols/windows/pdbconv.py", line 838, in replace_forward_references
    return types.size // self.get_size_from_index(element_type)
  File "volatility/framework/symbols/windows/pdbconv.py", line 650, in get_size_from_index
    raise ValueError("Unable to determine size of leaf_type {}".format(leaf_type.lookup()))
ValueError: Unable to determine size of leaf_type LF_ARGLIST
```

The name of the type being processed was `\x04` which may therefore be an earlier parsing error, but more investigation is required.

**Comment by ikelos** [comment]
Ok, hopefully this has been resolved.  Just going to wait on testing to find out...  5:)

**Comment by ikelos** [comment]
Testing seemed to work fine, remaining issues were actually to do with the ELF layer.
