### ISSUE TITLE
Cache FileNotFoundError

### ISSUE THREAD

**Issue by SheWil709** [volatilityfoundation/volatility3#994]
I currently have a Windows 11 memory dump, which is the only one that does not work. I downloaded the PDB online, converted the .blob to .json.xz. Below is the output when I tried to run --clear-cache, but I get the same error without that argument. Any assistance would be greatly appreciated.

```
PS C:\Users\FOR\Desktop\volatility3> python.exe .\vol.py --clear-cache -f G:\Test_Dumps\personal\memdump.dmp windows.info
Volatility 3 Framework 2.5.0
WARNING  volatility3.framework.plugins: Automagic exception occurred: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\FOR\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Roaming\\volatility3\\data_76ea0cc7de9b33e45300614d7e4110ee6fa129ece9928042753da54950146035c8bc7bfc6bf8ec75b70083d4820419accdf9b5d6197bb3de72384970fa262cd9.cache'

Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']
```

```
PS C:\Users\FOR\Desktop\volatility3> python.exe .\vol.py -vvvvv -f G:\Test_Dumps\personal\memdump.dmp windows.info
Volatility 3 Framework 2.5.0
INFO     volatility3.cli: Volatility plugins path: ['C:\\Users\\FOR\\Desktop\\volatility3\\volatility3\\plugins', 'C:\\Users\\FOR\\Desktop\\volatility3\\volatility3\\framework\\plugins']
INFO     volatility3.cli: Volatility symbols path: ['C:\\Users\\FOR\\Desktop\\volatility3\\volatility3\\symbols', 'C:\\Users\\FOR\\Desktop\\volatility3\\volatility3\\framework\\symbols']
Level 7  volatility3.cli: Cache directory used: C:\Users\FOR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Roaming\volatility3
INFO     volatility3.framework.automagic: Detected a windows category plugin
INFO     volatility3.framework.automagic: Running automagic: ConstructionMagic
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
INFO     volatility3.framework.automagic: Running automagic: SymbolCacheMagic
INFO     volatility3.framework.automagic: Running automagic: LayerStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 7  volatility3.framework.layers.resources: Available URL handlers: HTTPErrorProcessor, HTTPDefaultErrorHandler, HTTPRedirectHandler, ProxyHandler, HTTPBasicAuthHandler, ProxyBasicAuthHandler, HTTPDigestAuthHandler, ProxyDigestAuthHandler, AbstractHTTPHandler, HTTPHandler, HTTPSHandler, HTTPCookieProcessor, UnknownHandler, FileHandler, FTPHandler, CacheFTPHandler, DataHandler, VolatilityHandler, JarHandler, OfflineHandler, LeechCoreHandler
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using XenCoreDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Stacked WindowsCrashDump64Layer using WindowsCrashDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using XenCoreDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using WindowsIntelStacker
DEBUG    volatility3.framework.automagic.windows: Detecting Self-referential pointer for recent windows
DEBUG    volatility3.framework.automagic.windows: DtbSelfRef64bit test succeeded at 0x1ae000
DEBUG    volatility3.framework.automagic.windows: DTB was found at: 0x1ae000
Level 8  volatility3.framework.automagic.stacker: Stacked IntelLayer using WindowsIntelStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using AVMLStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using Elf64Stacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using XenCoreDumpStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using LimeStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using QemuStacker
Level 8  volatility3.framework.automagic.stacker: Attempting to stack using VmwareStacker
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name.memory_layer
Level 9  volatility3.framework.configuration.requirements: IndexError - No configuration provided: plugins.Info.kernel.layer_name.memory_layer.base_layer
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_virtual_offset requirements only accept int type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.interfaces.configuration: TypeError - kernel_banner requirements only accept str type: None
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info.kernel
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.automagic.construct_layers: Failed on requirement: plugins.Info
DEBUG    volatility3.framework.automagic.stacker: Stacked layers: ['IntelLayer', 'WindowsCrashDump64Layer', 'FileLayer']
INFO     volatility3.framework.automagic: Running automagic: WinSwapLayers
INFO     volatility3.framework.automagic: Running automagic: KernelPDBScanner
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
DEBUG    volatility3.framework.automagic.pdbscan: Kernel base determination - searching layer module list structure
DEBUG    volatility3.framework.automagic.pdbscan: Setting kernel_virtual_offset to 0xf80464200000
INFO     volatility3.framework.symbols.windows.pdbconv: Download PDB file...
DEBUG    volatility3.framework.symbols.windows.pdbconv: Attempting to retrieve http://msdl.microsoft.com/download/symbols/ntkrnlmp.pdb/E0093F3AEF15D58168B753C9488A40431/ntkrnlmp.pdb
DEBUG    volatility3.framework.layers.resources: Caching file at: C:\Users\FOR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Roaming\volatility3\data_76ea0cc7de9b33e45300614d7e4110ee6fa129ece9928042753da54950146035c8bc7bfc6bf8ec75b70083d4820419accdf9b5d6197bb3de72384970fa262cd9.cache
INFO     volatility3.framework.automagic: Running automagic: SymbolFinder
INFO     volatility3.framework.automagic: Running automagic: KernelModule
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
Level 9  volatility3.framework.configuration.requirements: Symbol table requirement not yet fulfilled: plugins.Info.kernel.symbol_table_name
WARNING  volatility3.framework.plugins: Automagic exception occurred: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\FOR\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Roaming\\volatility3\\data_76ea0cc7de9b33e45300614d7e4110ee6fa129ece9928042753da54950146035c8bc7bfc6bf8ec75b70083d4820419accdf9b5d6197bb3de72384970fa262cd9.cache'
Level 9  volatility3.framework.plugins: Traceback (most recent call last):
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\automagic\__init__.py", line 138, in run
    automagic(context, config_path, requirement, progress_callback)
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\automagic\pdbscan.py", line 448, in __call__
    self.recurse_symbol_fulfiller(
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\automagic\pdbscan.py", line 123, in recurse_symbol_fulfiller
    PDBUtility.load_windows_symbol_table(
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 114, in load_windows_symbol_table
    cls.download_pdb_isf(
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\symbols\windows\pdbutil.py", line 262, in download_pdb_isf
    filename = pdbconv.PdbRetreiver().retreive_pdb(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\symbols\windows\pdbconv.py", line 960, in retreive_pdb
    with resources.ResourceAccessor(progress_callback).open(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FOR\Desktop\volatility3\volatility3\framework\layers\resources.py", line 182, in open
    with open(temp_filename, "wb") as cache_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\FOR\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Roaming\\volatility3\\data_76ea0cc7de9b33e45300614d7e4110ee6fa129ece9928042753da54950146035c8bc7bfc6bf8ec75b70083d4820419accdf9b5d6197bb3de72384970fa262cd9.cache'


Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']
```

**Comment by SheWil709** [comment]
Update: I went back and re-installed Volatility3 Framework 2.4.1 instead of 2.5, and it worked!

**Comment by ikelos** [comment]
Hmmm, glad you got it working, but it's a little troubling that something changed to cause it to fail, but I don't recall have tinkered in an area of code that might have that effect.  5:S  It sounds like a file permission issue in some way (the cache writer should have written the file at the line 
```
DEBUG    volatility3.framework.layers.resources: Caching file at: C:\Users\FOR\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\Roaming\volatility3\data_76ea0cc7de9b33e45300614d7e4110ee6fa129ece9928042753da54950146035c8bc7bfc6bf8ec75b70083d4820419accdf9b5d6197bb3de72384970fa262cd9.cache
```
But then shortly after the file isn't present.  If you'd be happy to help us test, it would be interesting to upgrade to the latest development release (2.5.0) it would be helpful to know if the issue still happens (so whether it was just the reinstall or actually the version number that fixed the problem).  5:S

**Comment by kenjd05** [comment]
Hi, I got the same error using the volatility 2.4.1. How can i fix this?

PS C:\volatility3-2.4.1\volatility3-2.4.1> python.exe .\vol.py -f C:\volatility3-2.4.1\testdump.mem windows.info
Volatility 3 Framework 2.4.1
WARNING  volatility3.framework.plugins: Automagic exception occurred: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\personal\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\Roaming\\volatility3\\data_0123c78d6bbd0a9900ebd4167afe89f5a8c8716e7483fd0cbeed3221b45a9278349a34a038b3d8737445ef7e6a6f294c7dec1f716323f59f8534ad4bf8fd348c.cache'

Unsatisfied requirement plugins.Info.kernel.symbol_table_name:

A symbol table requirement was not fulfilled.  Please verify that:
        The associated translation layer requirement was fulfilled
        You have the correct symbol file for the requirement
        The symbol file is under the correct directory or zip file
        The symbol file is named appropriately or contains the correct banner

Unable to validate the plugin requirements: ['plugins.Info.kernel.symbol_table_name']

**Comment by ikelos** [comment]
It's quite possibly it's having difficulty writing to that directory.  You can use `--cache-path` to point to a writable directory, and if that works then we can look into ensure that errors there don't stop the whole program...

**Comment by fzlaziz** [comment]
> It's quite possibly it's having difficulty writing to that directory. You can use `--cache-path` to point to a writable directory, and if that works then we can look into ensure that errors there don't stop the whole program...

how to do that? right now I'm having the same issue
"No such file or directory: 'C:\Users\Username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11........"

**Comment by ikelos** [comment]
You'd run `vol.py --cache-path "C:\Temp" -f <path-to-image> <plugin>` as long as C:\Temp existed...
